### ISSUE TITLE
Maps are still getting set back to not fill the full page

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#164]
Edited by @runjak:
Maps are still getting set back to not fill the full page. The error seems to arise only when switching from 1 language view back to Map view, so it's 1 language view that it somehow resetting what the map scales to.

**Comment by PaulHeggarty** [comment]
At least I've found out what is causing this, and it is now reproducible at will.  Just switch to 1 language view and back to map view.

**Comment by runjak** [comment]
I have a fix for this and will deploy it soon.
Usual browser cache problematic applies.

**Comment by PaulHeggarty** [comment]
There is one more event sequence that still triggers this problem:
![screenshot - 2016-06-22 15_36_09](https://cloud.githubusercontent.com/assets/8819910/16268585/46d0e2d8-388f-11e6-927b-5e5e8a1025ca.png)

How that happened is that I had changed view to 1-Language table view, then hit the back button on my browser, then I got the result in the image above.  Whether it's worth investing much time in trying to fix this I don’t know, but if it ever happens to users, they might not know how to 'fix' it, and be stuck with the map like this. But if there's an easy way of triggering the resize event if necessary on a back or forward command, it would be good.

**Comment by runjak** [comment]
I have a piece of code that fixes this behavior and will close this issue after deployment.
It appears to be a hard task to catch all events that make it necessary to resize the map.
To mitigate this I've added a check that runs every second when the map is viewed to check that the map size is correct and to correct it if possible.
