### ISSUE TITLE
Not working sample "Oberdeutsch: (Nieder-) Alemannisch: (zentraler) Elsass: Mittach"

### ISSUE THREAD

**Issue by LauraWae** [lingdb/Sound-Comparisons#180]
This sample is not working on the website, although the corresponding file is uploaded on the server. My proposal is to check the spelling of the name of the sample in the database of the website, because here it says "Mittach" instead of "Mittlach" (the name of the soundfile folder is: Gmc_W_GHgh_Alm_H_AlsaceS_Mittlach_Dl)

**Comment by runjak** [comment]
It appears that in the current database the entry for this is `Gmc_W_GHgh_Alm_L_AlsCMittlach_Dl`.
![db](https://cloud.githubusercontent.com/assets/5417642/9789332/c7eb6952-57cf-11e5-823e-c492be7a2cae.png)
I think this would be something for @PaulHeggarty to adjust.
