### ISSUE TITLE
[Select all words in this set] does not work, even though individual words can be added to a LgsxWds table

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#241]

**Comment by runjak** [comment]
The structure for the links that perform the selection of words here is such,
that there is an `<a href="…"><i class=""></i></a>`, and a click on the `<i>` element doesn't appear to trigger a click event on the `<a>` element.
I should be able to fix this easily by adding click listeners to the `<i>` elements that trigger the parent `<a>`.

**Comment by PaulHeggarty** [comment]
Seems fixed.
