### ISSUE TITLE
Maps by default still do not zoom in enough

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#245]

**Comment by PaulHeggarty** [comment]
This still does not seem to work, and it's now pretty urgent for the offline version especially.  A clear test case is Romance. The default settings are for latitudes of maximum 52 North, minimum 32 North.  But the map defaults, and resets when clicking 'Core Region', to something like 66 North (cutting through Iceland) and 10 North (the middle of Sudan).  
Now this could be understandable if the longitude span was so wide, and the screen narrow, but the longitudes are also fine. They are set in the database to 10 West and 30 East, which should put Portugal very near the left edge, and Romania on the right edge.  Instead, we get way out into the Atlantic Ocean, clipping the Azores, and east all the way to Pakistan.
Interestingly, what is right is that the core region is reasonably centred on the screen, but the margins of space all round it are far bigger than they should be.
Or is it because one can only scale to fixed zoom levels, not a customised one? So if even just one more click on the zoom level button would cause the screen not to accommodate either the full latitude or the full longitude range, then it scales back out again to the next level out?
![screenshot - 2016-06-22 13_14_55](https://cloud.githubusercontent.com/assets/8819910/16265012/3acce070-387d-11e6-8c55-d8647d70815f.png)

There also seems to be some problem if one hides and re-shows the language and word selector columns.  The idea is to make more space for the map (or table) in the main central frame, but the map redrawing doesn’t seem to respond as it should.  I get results like this:
![screenshot - 2016-06-22 13_15_48](https://cloud.githubusercontent.com/assets/8819910/16265002/32cd77a4-387d-11e6-912b-03a40f4d2b48.png)

**Comment by PaulHeggarty** [comment]
I’ve experimented, and think in part we might just be unlucky with the coordinates for Romance.  I've changed the eastern limit from 30 to 25, and on my screen we suddenly default to a zoom level 1 closer in...  I’m now going to keep trying to fine-tune each family, but of course it depends also on screen size.

**Comment by PaulHeggarty** [comment]
Interestingly, having set Romance longitudes to -9 and 27, I now get this problem back again:
![screenshot - 2016-06-22 13_37_07](https://cloud.githubusercontent.com/assets/8819910/16265263/99653924-387e-11e6-9ba0-1b0e241b23f2.png)

**Comment by runjak** [comment]
This could be an issue related to map resizing.
I'll see how it can be solved.

**Comment by PaulHeggarty** [comment]
It's looking like it may be mostly a question of just the inflexibility of zoom levels, and me fine-tuning the exact lat-long limits for the default view for each family.
However, there also needs to be a map reset/resize event triggered properly when hiding/showing the word selector and language selector columns. It already works perfectly with the table views, but not with the map view, so presumably something can be copied from how it works in table views.

**Comment by runjak** [comment]
I have a piece of code that fixes the resize issue that arises when the side menus are hidden/displayed again. This issue will be closed after deployment.
