### ISSUE TITLE
Figure out authentication with flask

### ISSUE THREAD

**Issue by runjak** [lingdb/Sound-Comparisons#251]
Since the switch to flask is also meant to enable integration with the ielex2 effort,
we need something new and shiny for authentication and authorization.
There was already some talk about using oauth here.

**Comment by runjak** [comment]
With the recent addition of [lingdb/flask-oauth](https://github.com/lingdb/flask-oauth) I should now be able to figure out how to integrate oauth authentication for soundcomparisons with flask.

**Comment by runjak** [comment]
Since cb3b76bcb88719dc1388185f747e4c2dd5e050d5 the main question here is how and where to store user data.

**Comment by xrotwang** [comment]
We'll rather switch to a clld backend than a flask one.
