### ISSUE TITLE
Google Maps have brought back the slider (on a click). Put back on our maps!

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#292]
Google maps has brought back the zoom slider:  hovering over the +/- buttons give you the option to show slider.  I'd like it to appear on our maps by default, if possible.  But not change anything else, like terrain view, and the limited display of labels.

**Comment by runjak** [comment]
There is a [zoomslider](https://kartena.github.io/Leaflet.zoomslider/) available for leaflet which could provide the wanted functionality.

**Comment by PaulHeggarty** [comment]
The zoomslider looks good, yes please!
