### ISSUE TITLE
Adjust colors for language groups

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#298]
Edited by @runjak:
Colour for language groups 4 Yellow and 5 Pale Green are not distinct enough on maps.
5 needs to be a bit deeper green.

**Comment by runjak** [comment]
In contrast to the database issues this is a change in JavaScript that is currently being cached.
I think I have an idea about fixing the cache situation for JavaScript as well, and will likely look into it next. I've adjusted the color to be a different green. Compare the screenshots:
![c1](https://cloud.githubusercontent.com/assets/5417642/13219486/a0e91264-d970-11e5-86c6-4339288ffce3.png) ![c2](https://cloud.githubusercontent.com/assets/5417642/13219488/a29a625c-d970-11e5-91a1-549c39982ec9.png)
