### ISSUE TITLE
DefaultLanguagesToExcludeFromMap does not work

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#299]
I've identified a set of languages to exclude from the map for Malakula, and uploaded the DefaultLanguagesToExcludeFromMap file, but the languages always still show.  I've cleared server and my cache, force reload, no difference.

**Comment by runjak** [comment]
I've found that this is the same problem as #302, and has been fixed in b4c7d0655bd0f202d7c7718967be6889b7bb80cd.
The defaults should work as expected after deployment.
