### ISSUE TITLE
Column widths are badly distributed in 1 Lg view

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#303]
This is particularly obvious for the Malakula languages, although it actually affects all studies.
Note how wide the first column is, and how narrow the other two, on this page, for example:
[http://www.soundcomparisons.com/#/en/Malakula/language/Ndarmif]
I presume this is because of the slightly long text in one entry in the first column, "we (me, you, + others)…", but this is still nowhere near long enough to trigger this width of column.  
Also, this problem means that only three columns are shown on the page, when in fact many more could fit, and all words could be shown on one screen.

**Comment by runjak** [comment]
Wow, yes - this is horrible.
![screenshot_2016-02-22_11-44-56](https://cloud.githubusercontent.com/assets/5417642/13216052/bed48798-d959-11e5-96f3-8f5102901483.png)

**Comment by runjak** [comment]
I was able to mitigate this a bit by adjusting the css rules but while more elements are displayed per column, the columns are still of different widths which I find irritating.
![better](https://cloud.githubusercontent.com/assets/5417642/13216322/5fbc3416-d95b-11e5-97d5-13d9fc973b25.png)
