### ISSUE TITLE
Set default phonetics search/filter language to default single language

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#304]
There is already a setting for default langauge to show in 1-Language view, so set the default language in the phonetics search/filter box to the same language for now.  I do actually have a table in my database for default phonetics language, but it's not implemented yet in the tables I upload.
Also, currently if there is no default language set, it defaults to the first language, but it should default to the first for which phonetic transcriptions do actually exist ;)

**Comment by runjak** [comment]
Currently we use the first language that has `IsOrthographyHasNoTranscriptions == 0` set.
I will adjust this as requested.
