### ISSUE TITLE
SQL upload fails - file too large?

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#307]
I've just tried to upload an SQL file with 1143 lines, each longer now than they used to be because of the corrected update script.  File size 1.3 MB.  The result is an upload error:
```
413 Request Entity Too Large
nginx/1.9.7
```

**Comment by runjak** [comment]
I've made a [commit](https://github.com/lingdb/container/commit/fba4673394ed3fef2e8151f127f613d69e4cc5ce) to the container repo that should fix this problem and set the allowed file upload size to 10 mb.
