### ISSUE TITLE
Adding a 0 Lg Set removes Lg Set 1 for Malakula

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#312]
I've just added Lg Set 0, Reference languages, and Lg Set 1 (north) has disappeared.

**Comment by runjak** [comment]
Can you show/send me the data that you've imported/added?
I'm currently having trouble getting access to the VPN,
but will likely try later from home to see if it's a ramification with the university network.
I do however see, that a `North` set is not available in Malakula:
![sets](https://cloud.githubusercontent.com/assets/5417642/13529559/398254a4-e21d-11e5-967b-72cdab6b20ce.png)
I can also verify that the `North` region still appears to exist:
![regions](https://cloud.githubusercontent.com/assets/5417642/13529620/810e6d94-e21d-11e5-9bb9-6d6fe87925ee.png)
The reason for this behaviour appears to be that there are no languages linked to the `North` region, as demonstrated by below code sample:
![reason](https://cloud.githubusercontent.com/assets/5417642/13529702/cdaac4f4-e21d-11e5-82e0-8fe833a149a3.png)
Is it possible that your insertion of the `Reference` set somehow dropped the entries linking regions to the `North` set of regions?

**Comment by PaulHeggarty** [comment]
Sorry, false alarm!  I only noticed this when I uploaded the new 0 Languages set.  But in fact, that was not the cause!  Language Set 1 (North) had already disappeared because of changes made by others to the languages list.  They had turned off all languages in the north group, So no wonder it wasn't showing.  I've reactivated some, and it works fine now.  Sorry.
