### ISSUE TITLE
About pages stay in middle frame when other views are clicked

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#313]
![screenshot - 08_03_2016 20_24_40](https://cloud.githubusercontent.com/assets/8819910/13613325/e8b36df4-e56b-11e5-9d0c-e74c9b0f1110.png)

**Comment by runjak** [comment]
Ah, I see. I think I already know the fix for this.
Too stupid that I didn't test this feature enough.
