### ISSUE TITLE
Fix dimensions but on speaker portrait photos 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#318]
Especially for the Malakula project, we have photos of lots of the speakers of individual language recordings.  
These should be displayed in two, perhaps three places -- but the priority is (2), not (1):

1.  In 1-language view, by a new, separate icon -- actually a thumbnail of the photo -- immediately in front of the current icon for contributors.  When hovering over the thumbnail, the full-size picture should pop up in a 'bubble' (with slightly rounded corners).

2. In the language selector column (to make it possible to see all speakers without changing page).  When one clicks on a language name in the language selector column (say in map view), it currently shows two icons next to that language name (to re-centre the map for that language, or switch to 1-language view for it).  We need to add another icon, in front of the existing two in fact, which is again actually the thumbnail of the portrait photo.  Again, hovering on it will expand to the full-size image. 

3. Perhaps we should also consider somehow (Ctrl-Hover?) showing photos from the transcription bubbles or black dots on the map itself,

***Image filenames
The actual photo image files will be named with the same filename string as for the recording sound files, e.g. Oce_Van_Mal_Int_Sth_Letemboi_Aingelemolesa_Dl, followed by _ and then two digits, then .jpg

The two digits allow for multiple photos.  _01 would normally be the speaker portrait, higher numbers would include photos of the village, perhaps.  

***Image size/resolution
It would be good to have images that are not too big, perhaps something in the range of 600-800 pixels, or even 400 or so.  That would be best for speed and size, especially given how slow internet connections are in Malakula itself, for anyone wanting to use this feature from the island itself.  Files should be reduced to this size before sending to Sound Comparisons.  

***Deadline
We'd really like to get this done in time for when Russell is back on 31st March 2016.

**Comment by runjak** [comment]
Ok, so I went ahead and did some implementation for point 2.
Are there already some images available on the server or to me that I can test with?

**Comment by PaulHeggarty** [comment]
No photos yet, I think.  Just test with the photos we already have for contributors?

**Comment by PaulHeggarty** [comment]
Images should be going into:
… OwnCloud\SndComp\Malakula\x Photo portraits of participants

Only two there for the moment, and wrongly named.  But should get fixed soon.
Also, is it possible to add a caption at the bottom, showing the speaker's name -- which will be drawn in from the Contributors table, as the speaker for that language?

**Comment by runjak** [comment]
Ok, so with the OwnCloud link I was able to get some images onto the server.
When you click on a language in the left menu in MapView, you can get a preview icon like this:
![screenshot_2016-03-25_10-16-06](https://cloud.githubusercontent.com/assets/5417642/14041609/f1e9f9ce-f272-11e5-883e-6c89a448caf2.png)
When clicking on that preview icon you get a dialog displaying the corresponding image full size.
![screenshot_2016-03-25_10-16-16](https://cloud.githubusercontent.com/assets/5417642/14041610/f1ea078e-f272-11e5-8b3a-e626eae75e68.png)
The drawback on the current setup is that the dialog tends to be smaller than the image so that scrolling is necessary. This is something I will fix soon but not today.

**Comment by AvivaShimelman** [comment]
Looking forward to seeing it! 

I've uploaded appropriately-named jpg's for all those recordings that already have SC names. Unfortunately, I just don't have portraits for most of the languages that are already on the site. I began systematically taking photos only this year, and the recordings that are up are from last year. The portraits are nice -- I think -- and have a uniform style, but we won't be able to populate the site completely (I think we can anticipate having about 65% coverage by the time all the recordings from last year and this get up).  I'm sorry -- I just didn't anticipate that they would get used. I sent them to Russell as a "by-the-way" and he was inspired to get them up on the site.

I'd like to make make two subfiles in the portraits file -- one will contain all the portraits that have SC-ready names; the second will be for storing portraits that will eventually be assigned SC names. The latter will have my labels (pinned to my recording numbers and labeled by language and dialect). This is a way of storing them, yes, but also a way of making them available for re-labeling by anyone else (Laura?), as soon as recordings are assigned codes.

Aviva

**Comment by PaulHeggarty** [comment]
This seems to be taking too long, and much more of your time, Jakob, than anticipated.  If I had known how long, I would have waited.  Best get back to CoBL stuff, levels 1 and 2, before this.

**Comment by PaulHeggarty** [comment]
The problem of the dimensions not working now urgently needs fixing, please.
![screenshot - 04_06_2016 21_35_27](https://cloud.githubusercontent.com/assets/8819910/15898439/a21dee62-2d98-11e6-838d-5b4c0d94fe58.png)

**Comment by PaulHeggarty** [comment]
Loads more photos have now been uploaded to the folder on OwnCloud.
They vary a great deal in dimensions, however.  @runjak, is this OK or should they be standardised?
Also, some of the filenames are wrong: there are two that include a hyphen, for example, but no filename should include a hyphen.

**Comment by PaulHeggarty** [comment]
The rule is:  don’t type in a language name manually anywhere.  Always cut and paste from the actual name in a reference sheet or a file itself.  That way we avoid bugs like this that can otherwise slip by unnoticed and then waste much more time fixing later.

**Comment by AvivaShimelman** [comment]
With regard to the hyphens, it looks like those are "leftovers." I don't
think they could be interfering with anything because it shouldn't be
"looking for" them.  "Atchin-Tautu" isn't a recording we're using and
neither is WalaPreng. All the others were cut and pasted yesterday
(exception "_01" was added by hand).

I can re-cut the photos if necessary. Indeed, they were all just eye-balled
based on facial dimentions.

A.

A.

On Wed, Jun 22, 2016 at 10:26 AM, Paul Heggarty <notifications@github.com>
wrote:

> Loads more photos have now been uploaded to the folder on OwnCloud.
> They vary a great deal in dimensions, however. @runjak
> <https://github.com/runjak>, is this OK or should they be standardised?
> Also, some of the filenames are wrong: there are two that include a
> hyphen, for example, but no filename should include a hyphen.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/318#issuecomment-227676542>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM_k3ebhu-gAjkdZVyMYW6aswnpYCks5qOPHHgaJpZM4Hw-32>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment]
Please let me know if you need me to re-crop the photos (or do anything
else with them).  A.

On Wed, Jun 22, 2016 at 10:26 AM, Paul Heggarty <notifications@github.com>
wrote:

> Loads more photos have now been uploaded to the folder on OwnCloud.
> They vary a great deal in dimensions, however. @runjak
> <https://github.com/runjak>, is this OK or should they be standardised?
> Also, some of the filenames are wrong: there are two that include a
> hyphen, for example, but no filename should include a hyphen.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/318#issuecomment-227676542>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM_k3ebhu-gAjkdZVyMYW6aswnpYCks5qOPHHgaJpZM4Hw-32>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by runjak** [comment]
I've updated the photos on the server and have verified that more are displayed now.
From the size they all appeared to work OK on my machine.
I'll check the data generated by the server to see if there are photos in the folder now that are not found.

**Comment by AvivaShimelman** [comment]
Thanks. I only started taking photos this year, so not all recordings will
have photos.

On Wed, Jun 22, 2016 at 2:31 PM, Jakob Runge <notifications@github.com>
wrote:

> I've updated the photos on the server and have verified that more are
> displayed now.
> From the size they all appeared to work OK on my machine.
> I'll check the data generated by the server to see if there are photos in
> the folder now that are not found.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/318#issuecomment-227728552>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM80tIqz_hgO2MJNf9QqU_dFFkgQuks5qOSsrgaJpZM4Hw-32>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by runjak** [comment]
There are photos we have that are not recognized by the server:
```
Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl_01.jpg
Oce_Van_Mal_East_SCtr_Nitita_Khatbol_Dl.jpg
Oce_Van_Mal_Int_Nth_Batarxopu_Lembilmbil_Dl_01.jpg
Oce_Van_Mal_Int_Nth_Njav_Tanmililib_Dl_01.jpg
Oce_Van_Mal_Nth_DNth_AlavasWowo_AlavasAlavas2_Dl_01.jpg
Oce_Van_Mal_Nth_DNth_AlavasWowo_WowoLesarmalas_Dl_01.jpg
Oce_Van_Mal_Nth_ENth_Vao_Peteri_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_Tirax_Bethel_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_Tirax_MaeBethel_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_Tirax_Orap_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_Atchin-Tautu_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_Rano_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_UripivTautu_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_WalaPetreros_Dl_01.jpg
Oce_Van_Mal_Nth_ESth_UWRA_Wala-Preng_Dl_01.jpg
Oce_Van_Mal_Nth_Nth_Alavas_Alavas_Dl.jpg
Oce_Van_Mal_Nth_WNth_Nese_Matanvat_Dl_01.jpg
Oce_Van_Mal_Nth_WNth_Nese_Sanboise_Dl_01.jpg
Oce_Van_Mal_Nth_WSth_Taute_Benenavet_Dl_01.jpg
Oce_Van_Mal_Nth_WSth_Taute_Benwara_Dl_01.jpg
Oce_Van_Mal_Nth_WSth_Taute_Taute_Dl_01.jpg
Oce_Van_Mal_Nth_WSth_Taute_Tenamet_Dl_01.jpg
Oce_Van_Mal_Nth_WSth_VenenTaute_North_Dl_01.jpg
```
Possible sources of this problem are:
* Maybe the Photos are outdated?
* Maybe the detection does not work as it should?
* Maybe the names are wrong?

What's your opinion on this, @AvivaShimelman?

**Comment by AvivaShimelman** [comment]
Indeed, all of them are old. I pulled them off of owncloud (although I now
realize I shouldn't have done that) when I uploaded all the photos
yesterday with their new labels.

On Wed, Jun 22, 2016 at 2:50 PM, Jakob Runge <notifications@github.com>
wrote:

> There are photos we have that are not recognized by the server:
>
> Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl_01.jpg
> Oce_Van_Mal_East_SCtr_Nitita_Khatbol_Dl.jpg
> Oce_Van_Mal_Int_Nth_Batarxopu_Lembilmbil_Dl_01.jpg
> Oce_Van_Mal_Int_Nth_Njav_Tanmililib_Dl_01.jpg
> Oce_Van_Mal_Nth_DNth_AlavasWowo_AlavasAlavas2_Dl_01.jpg
> Oce_Van_Mal_Nth_DNth_AlavasWowo_WowoLesarmalas_Dl_01.jpg
> Oce_Van_Mal_Nth_ENth_Vao_Peteri_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_Tirax_Bethel_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_Tirax_MaeBethel_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_Tirax_Orap_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_Atchin-Tautu_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_Rano_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_UripivTautu_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_WalaPetreros_Dl_01.jpg
> Oce_Van_Mal_Nth_ESth_UWRA_Wala-Preng_Dl_01.jpg
> Oce_Van_Mal_Nth_Nth_Alavas_Alavas_Dl.jpg
> Oce_Van_Mal_Nth_WNth_Nese_Matanvat_Dl_01.jpg
> Oce_Van_Mal_Nth_WNth_Nese_Sanboise_Dl_01.jpg
> Oce_Van_Mal_Nth_WSth_Taute_Benenavet_Dl_01.jpg
> Oce_Van_Mal_Nth_WSth_Taute_Benwara_Dl_01.jpg
> Oce_Van_Mal_Nth_WSth_Taute_Taute_Dl_01.jpg
> Oce_Van_Mal_Nth_WSth_Taute_Tenamet_Dl_01.jpg
> Oce_Van_Mal_Nth_WSth_VenenTaute_North_Dl_01.jpg
>
> Possible sources of this problem are:
>
>    - Maybe the Photos are outdated?
>    - Maybe the detection does not work as it should?
>    - Maybe the names are wrong?
>
> What's your opinion on this, @AvivaShimelman
> <https://github.com/AvivaShimelman>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/318#issuecomment-227732816>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM77Klg9B02AtpI5va5eMXcroPYKZks5qOS-kgaJpZM4Hw-32>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by runjak** [comment]
Ok - I'll make sure they also get deleted from the server.

**Comment by runjak** [comment]
This issue will get closed automagically once the images are removed from the server.
