### ISSUE TITLE
Make mapping data storable offline, by switching map system?

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#319]
See -- and discuss with Hans-Jörg -- how to perhaps implement the map system, with a choice of many mapping data and layers, used in many existing CLLD projects, as for example at:
http://wals.info/feature/1A#2/19.3/152.8
It would also be great (though perhaps best left for a second stage), if this system could also be used:
http://maps-for-free.com/?val=-15,-75
This is not super-urgent, but certainly is necessary to get working in the offline version before Aviva returns to Vanuatu at the end of June.

**Comment by runjak** [comment]
By using [leaflet.js](leafletjs.com) together with [openstreetmap](openstreetmap.org) I consider this issue solved now.
