### ISSUE TITLE
Progress tracker issue for *mark-up* and *sound-file upload* of all new Malakula languages

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#320]
Laura: please enter as a comment here a list of all Malakula languages (preferably by their long filename) that still remain to be marked up (for all 215 meanings), and the sound files uploaded to the website.
Then as you complete each language and upload the soundfiles, add a new comment to this issue to indicate that that language has been completed.  This is to work as a progress tracker.

**Comment by LauraWae** [comment]
**All files**
Oce_Van_Bislama_Std
Oce_Van_Mal_Nth_WSth_Taute_Taute_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Rano_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Uripiv_Dl
Oce_Van_Mal_Nth_ESth_Tirax_Orap_Dl
Oce_Van_Mal_Nth_ESth_Tirax_MaeBethel_Dl
Oce_Van_Mal_West_NCtr_Neveei_Vinmavis_Dl
Oce_Van_Mal_West_Ctr_Novol_DixonReef_Dl
Oce_Van_Mal_West_Ctr_Novol_Melaklak_Dl
Oce_Van_Mal_West_Ctr_Nasarian_Wileven_Dl
Oce_Van_Mal_West_Ctr_Angavae_DixonReef_Dl
Oce_Van_Mal_West_SCtr_Nahavaq_Banour_Dl
Oce_Van_Mal_West_SCtr_Nahavaq_Lembinwin_Dl
Oce_Van_Mal_West_SCtr_Nahavaq_WhiteSandsWitava_Dl
Oce_Van_Mal_West_SCtr_Nahavaq_CarolineBayLumo_Dl
Oce_Van_Mal_West_SCtr_Nahavaq_Elu_Dl
Oce_Van_Mal_West_SCtr_Naati_Windua_Dl
Oce_Van_Mal_West_SCtr_Ninde_Lawa_Dl
Oce_Van_Mal_West_SCtr_Ninde_Opmobamba_Dl
Oce_Van_Mal_West_SCtr_Ninde_Labo_Dl
Oce_Van_Mal_West_SCtr_Ninde_Lorlo_Dl
Oce_Van_Mal_West_SCtr_Ninde_Windua_Dl
Oce_Van_Mal_East_NCtr_Neverver_LingarakhSakan_Dl
Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl
Oce_Van_Mal_East_NCtr_Neverver_LingarakhMindu_Dl
Oce_Van_Mal_East_NCtr_Tape_Tautu_Dl
Oce_Van_Mal_East_Ctr_Naman_Litzlitz_Dl
Oce_Van_Mal_East_SCtr_Unua_Noferai_Dl
Oce_Van_Mal_East_SCtr_Unua_Mbatumbo_Dl
Oce_Van_Mal_East_SCtr_Pangkumu_Datisman_Dl
Oce_Van_Mal_East_SCtr_Pangkumu_Ndarmif_Dl
Oce_Van_Mal_East_SCtr_Nitita_Khatbol_Dl
Oce_Van_Mal_East_SCtr_Fifti_Khatbol_Dl
Oce_Van_Mal_East_SCtr_Tesmbol_Melaklak_Dl
Oce_Van_Mal_East_SCtr_Tesmbol_Usus_Dl
Oce_Van_Mal_Int_Nth_Ia_Benut_Dl
Oce_Van_Mal_Int_Nth_Ia_Lebilbil_Dl
Oce_Van_Mal_Int_Sth_Letemboi_Natingatlang_Dl
Oce_Van_Mal_Int_Sth_Letemboi_Aingelemolesa_Dl
Oce_Van_Mal_Int_Sth_Letemboi_Newotenyene_Dl
Oce_Van_Mal_Int_Sth_Letemboi_Nevatanyene_Dl
Oce_Van_Mal_Mlt_Avava_Khatbol_Dl
Oce_Van_Mal_Mlt_Avava_Gavai_Dl
Oce_Van_Mal_Mlt_Avava_Tisvel_Dl
Oce_Van_Mal_Mlt_Avava_Salang_Dl
Oce_Van_Mal_Mlt_Avava_Diver_Dl
Oce_Van_Mal_Mlt_Avava_Bangaasak_Dl
Oce_Van_Mal_Mlt_Avava_Tembibi_Dl
Oce_Van_Mal_Mlt_Nombotkote_Melaklak_Dl
Oce_Van_Mal_Mlt_Nombotkote_Blacksands_Dl
Oce_Van_Mal_Mlt_Nombotkote_Melkin_Dl

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl tagged and uploaded.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_ESth_Tirax_MaeBethel_Dl cleaned up and tagged.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_ESth_UWRA_Uripiv_Dl cleaned up and tagged.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl: working
Oce_Van_Mal_Nth_ESth_Tirax_MaeBethel_Dl: working
Oce_Van_Mal_Nth_ESth_UWRA_Uripiv_Dl: working, but numerals, adjectives and pronouns are missing. I investigate that.

**Comment by LauraWae** [comment]
Done Oce_Van_Mal_Nth_ESth_UWRA_Rano_Dl. All correct.

**Comment by LauraWae** [comment]
Done Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl: done.

**Comment by LauraWae** [comment]
Oce_Van_Mal_West_SCtr_Nahavaq_Banour_Dl done.
Oce_Van_Mal_Mlt_Avava_Tembibi_Dl done.

**Comment by AvivaShimelman** [comment]
RE: Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl
There's every likelihood that it is my fault, but this file is misleadingly named.  Maraxus is not a dialect of Neverver. In fact, as far as I can figure out, it's not a dialect of anything. Ethnologue and Glottolog list Tape (recorded last year -- Oce_Van_Mal_East_NCtr_Tape_Tautu_Dl) as an alternative name for Maraxus; the two, however -- eye-balling it -- are only about 25% cognate (same 25% as just about all the Malakula languages). Tape has three speakers left: Maraxus has just one.

My instinct here is to keep last year's files untouched -- Tape_Tautu will retain its ISO/Glottolog codes. Maraxus will receive the same codes, but the two will not be listed as different dialects of the same language. As I've set it up in the new "For pasting" spreadsheet, Maraxus would be designated:
Oce_Van_Mal_East_NCtr_Maraxus_Maraxus_Dl.
Sorry for the (suggested) switch.

**Comment by LauraWae** [comment]
Oce_Van_Bislama_Std cleaned up and uploaded.

**Comment by LauraWae** [comment]
wl_160064_Vao_04_Torono cleaned up and tagged.

**Comment by LauraWae** [comment]
wl_0004_Nombotkote_02 cleaned up and tagged.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_WNth_Najit_Matanvat_Dl cleaned up and uploaded.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_WNth_MaluaBay_Marasup_Dl cleaned up and uploaded.

**Comment by PaulHeggarty** [comment]
Looks like excellent progress.  I’ve put Marasup back on the website, but it appears in the sea well south of the island.  The latitude datum is clearly wrong (perhaps longitude too).  Can you check the lat-long, please.  Currently in as -16.75111, 167.5303.  Thanks.

**Comment by LauraWae** [comment]
Ok.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_WNth_MaluaBay_EspiegelsBay_Dl cleaned up and uploaded.

**Comment by AvivaShimelman** [comment]
Hold off, I'll double-check it.

On Wed, Mar 30, 2016 at 12:51 AM, Paul Heggarty <notifications@github.com>
wrote:

> Looks like excellent progress. I’ve put Marasup back on the website, but
> it appears in the sea well south of the island. The latitude datum is
> clearly wrong (perhaps longitude too). Can you check the lat-long, please.
> Currently in as -16.75111, 167.5303. Thanks.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/320#issuecomment-202902351>
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
wl_160025_Batarxopu_03_Benut_selected cleaned up and tagged.

**Comment by AvivaShimelman** [comment]
The language I originally designated as "Ia" is actually referred to by most of its speakers -- those that give it a name -- as "Batarxobu." So '"Ia" got swapped out everywhere for "Batarxobu." I don't think I made that clear -- I'm very sorry for the confusion.

**Comment by AvivaShimelman** [comment]
Excellent choice.

On Wed, Mar 30, 2016 at 6:59 AM, Paul Heggarty <notifications@github.com>
wrote:

> This can be changed superficially for now in the language names on the
> website. I won’t change it underlyingly in the fielname itself yet, because
> that requires a lot of fixing. We'll do that in May.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/320#issuecomment-203074621>
>



-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment]
Yes - Nothing on Malakula is west of 167.15/east of 167.85,  south of
-16.6/north of -15.88). Don't know how that got on there. It's corrected on
the new "for pasting" to:

-15.990983

167.219803

On Wed, Mar 30, 2016 at 12:51 AM, Paul Heggarty <notifications@github.com>
wrote:

> Looks like excellent progress. I’ve put Marasup back on the website, but
> it appears in the sea well south of the island. The latitude datum is
> clearly wrong (perhaps longitude too). Can you check the lat-long, please.
> Currently in as -16.75111, 167.5303. Thanks.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/320#issuecomment-202902351>
>



-- 
Aviva Shimelman, PhD

**Comment by PaulHeggarty** [comment]
It's fixed on the website map now.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Int_Nth_Ia_Benut_Dl extracted and uploaded.

**Comment by LauraWae** [comment]
wl_160034_TiraxB_07_Olam_selected cleaned up and tagged.

**Comment by LauraWae** [comment]
wl_160033_Siviti_02_Jericho_selected cleaned up and tagged.
@AvivaShimelman In this recording, you elicit two times "yutufala". The speaker gives two different answers, and I presume that one of those is actually "mitufala". Could you please check? You find the cleaned up file and the textgrid in Giovanni's folder.

**Comment by AvivaShimelman** [comment]
HI, Laura,

I can't download the file right now but I did check my copy of the
"selected" file. There are indeed two responses for "yutufala" (the second
corrects the first). There is no response for "mitufala" (if I later learn
that a speaker has made  mistake, I don't include the response in the
version of the file I send to you -- there are actually a lot of mistakes
with the pronouns).

Here are the prompts and their responses:

Yumitu - "nekir iru"

Mitufala - (none)

Yutufala - "kemi seru"

Tufala "xairpo iru"


I'm uploading a file with just these items now.


Thanks for catching it.


A.

On Thu, Mar 31, 2016 at 10:52 PM, LauraWae <notifications@github.com> wrote:

> wl_160033_Siviti_02_Jericho_selected cleaned up and tagged.
> @AvivaShimelman <https://github.com/AvivaShimelman> In this recording,
> you elicit two times "yutufala". The speaker gives two different answers,
> and I presume that one of those is actually "mitufala". Could you please
> check? You find the cleaned up file and the textgrid in Giovanni's folder.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/320#issuecomment-203896069>
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
Thanks a lot.

**Comment by LauraWae** [comment]
Cleaned up and tagged:
wl_160004_Uripiv_04_selected
wl_160022_Rano_04_Chinambon_selected
wl_160061_Alavas_04_Alavas_selected
wl_160062_Wowo_02_selected

**Comment by LauraWae** [comment]
wl_160064_Vao_04_Torono_selected cleaned up and tagged.

**Comment by LauraWae** [comment]
wl_160030_TiraxB_06_Bakru_selected cleaned up and tagged.

**Comment by LauraWae** [comment]
Cleaned up and tagged:
wl_160044_Taute_05_ALpalak_selected
wl_160027_Atchin_03_Lilrang_selected.

**Comment by LauraWae** [comment]
- wl_160061_Alavas_04_Alavas_selected renamed to Oce_Van_Mal_Nth_Nth_Alavas_Alavas_Dl. Extracted and uploaded.

- wl_160062_Wowo_02_selected renamed to Oce_Van_Mal_Nth_Nth_Alavas_Wowo_Dl. Extracted and uploaded.

**Comment by LauraWae** [comment]
This issue is now treated in #350. I will close it now.
