### ISSUE TITLE
Progress tracker issue for upload of first batch 52 *phonetic transcriptions* for all Malakula languages.

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#321]
Laura: please enter as a comment here a list of all Malakula languages (preferably by their long filename) for which transcriptions for the first 52 words already exist, but have not yet been entered into the 52-meaning Excel sheets, and transcriptions have not yet been uploaded to the website.
Then as you complete each language and upload the transcriptions, add a new comment to this issue to indicate that those language(s) have been completed and the transcriptions have been checked and do appear on the website.  
This issue is to work as a progress tracker.

**Comment by LauraWae** [comment]
Oce_Van_Mal_Nth_WSth_Taute_Taute_Dl: none
Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl: none
Oce_Van_Mal_Nth_ESth_UWRA_Rano_Dl: none
Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl: none
Oce_Van_Mal_Nth_ESth_UWRA_Uripiv_Dl: none
Oce_Van_Mal_West_SCtr_Nahavaq_Banour_Dl: done and working
Oce_Van_Mal_West_SCtr_Nahavaq_Lembinwin_Dl: done and working
Oce_Van_Mal_West_SCtr_Nahavaq_WhiteSandsWitava_Dl: none
Oce_Van_Mal_West_SCtr_Nahavaq_CarolineBayLumo_Dl: done and working
Oce_Van_Mal_West_SCtr_Nahavaq_Elu_Dl: none
Oce_Van_Mal_West_SCtr_Naati_Windua_Dl: done and working
Oce_Van_Mal_West_SCtr_Ninde_Lawa_Dl: done and working
Oce_Van_Mal_West_SCtr_Ninde_Opmobamba_Dl: done and working
Oce_Van_Mal_West_SCtr_Ninde_Labo_Dl: done and working
Oce_Van_Mal_West_SCtr_Ninde_Lorlo_Dl: none
Oce_Van_Mal_West_SCtr_Ninde_Windua_Dl: done and working
Oce_Van_Mal_West_NCtr_Neveei_Vinmavis_Dl: done and working
Oce_Van_Mal_West_Ctr_Novol_DixonReef_Dl: done and working
Oce_Van_Mal_West_Ctr_Novol_Melaklak_Dl: done and working
Oce_Van_Mal_West_Ctr_Nasarian_Wileven_Dl: done and working
Oce_Van_Mal_West_Ctr_Angavae_DixonReef_Dl: done and working
Oce_Van_Mal_East_NCtr_Neverver_LingarakhSakan_Dl: done and working
Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl: none
Oce_Van_Mal_East_NCtr_Neverver_LingarakhMindu_Dl: done and working
Oce_Van_Mal_East_NCtr_Tape_Tautu_Dl: done and working
Oce_Van_Mal_East_Ctr_Naman_Litzlitz_Dl: done and working
Oce_Van_Mal_East_SCtr_Unua_Noferai_Dl: done and working
Oce_Van_Mal_East_SCtr_Unua_Mbatumbo_Dl: done and working
Oce_Van_Mal_East_SCtr_Pangkumu_Datisman_Dl: done and working
Oce_Van_Mal_East_SCtr_Pangkumu_Ndarmif_Dl: done and working
Oce_Van_Mal_East_SCtr_Nitita_Khatbol_Dl: done and working
Oce_Van_Mal_East_SCtr_Fifti_Khatbol_Dl: done and working
Oce_Van_Mal_East_SCtr_Tesmbol_Melaklak_Dl: done and working, **missing word "ten"**
Oce_Van_Mal_East_SCtr_Tesmbol_Usus_Dl: done and working
Oce_Van_Mal_Int_Nth_Ia_Benut_Dl: none
Oce_Van_Mal_Int_Nth_Ia_Lebilbil_Dl: none
Oce_Van_Mal_Int_Sth_Letemboi_Natingatlang_Dl: done and working
Oce_Van_Mal_Int_Sth_Letemboi_Aingelemolesa_Dl: done and working
Oce_Van_Mal_Int_Sth_Letemboi_Newotenyene_Dl: done and working
Oce_Van_Mal_Int_Sth_Letemboi_Nevatanyene_Dl: done and working, **missing words "road" and "ten"**
Oce_Van_Mal_Mlt_Avava_Khatbol_Dl: done and working
Oce_Van_Mal_Mlt_Avava_Gavai_Dl: none
Oce_Van_Mal_Mlt_Avava_Tisvel_Dl: done and working
Oce_Van_Mal_Mlt_Avava_Salang_Dl: done and working
Oce_Van_Mal_Mlt_Avava_Diver_Dl: none
Oce_Van_Mal_Mlt_Avava_Bangaasak_Dl: done and working
Oce_Van_Mal_Mlt_Avava_Tembibi_Dl: done and working
Oce_Van_Mal_Mlt_Nombotkote_Melaklak_Dl: done and working
Oce_Van_Mal_Mlt_Nombotkote_Blacksands_Dl: done and working
Oce_Van_Mal_Mlt_Nombotkote_Melkin_Dl: none

**Comment by LauraWae** [comment]
**Investigating the Nones**:
Oce_Van_Mal_West_SCtr_Nahavaq_WhiteSandsWitava_Dl: no indication to Original file name on Reference Sheet.
Oce_Van_Mal_West_SCtr_Nahavaq_Elu_Dl: Original file name is wl_0023_Nahavaq_01, but such one cannot be found on Aviva's transcription list. --> check with Aviva?
Oce_Van_Mal_West_SCtr_Ninde_Lorlo_Dl: no Original file name on Reference Sheet
Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl: Original file is wl_160008_Maraxus_01, but such one cannot be found on Aviva's transcription list
Oce_Van_Mal_Int_Nth_Ia_Benut_Dl: Original file name is wl_160023_Batarxopu_01, but the same as above: no transcription can be found under that name in Aviva's transcription sheet.
Oce_Van_Mal_Int_Nth_Ia_Lebilbil_Dl: Original file name is wl_160024_Batarxobu_02; same as above.
Oce_Van_Mal_Mlt_Avava_Gavai_Dl: none
Oce_Van_Mal_Mlt_Avava_Diver_Dl: none
Oce_Van_Mal_Mlt_Nombotkote_Melkin_Dl: none

**Comment by LauraWae** [comment]
When I cross-entered the transcriptions from Avivas's transcription sheet (2016 03 15 SC Malakula 42 langs by 210 items with inflection), I found the following transcriptions that did not apply to any of the language names on the Reference sheet (2016 03 20 CURRENT  Malakula Languages Reference Sheet): 
Neveei 01
Ninde 02
Nombotkote 03
Novol 02
Novol 03
Neveei 02

**Comment by LauraWae** [comment]
**Oce_Van_Mal_West_SCtr_Nahavaq_WhiteSandsWitava_Dl
Oce_Van_Mal_West_SCtr_Ninde_Lorlo_Dl**
can be removed from the website for now, because Aviva does not have recordings for them. I ask her if she is planning to get them in the future.

**Oce_Van_Mal_Mlt_Avava_Gavai_Dl
Oce_Van_Mal_Mlt_Avava_Diver_Dl**
can be removed from the website once and for all due to lack of quality of the recordings.
@PaulHeggarty

**Comment by LauraWae** [comment]
Oce_Van_Mal_East_NCtr_Neverver_Maraxus_Dl (wl_160008_Maraxus_01): This is a recording from 2016. From that year, in general, we will receive transcriptions from Aviva at another point of the year.

**Comment by LauraWae** [comment]
**Oce_Van_Mal_West_SCtr_Nahavaq_Elu_Dl:** Original file name is **wl_0023_Nahavaq_01**, but such one cannot be found on Aviva's transcription list. --> check with Aviva? --> double naming with **Nahavaq_03**. I have changed that in the Reference sheet and in the transcriptions sheets. Case closed.

**Comment by AvivaShimelman** [comment]
Also from this year are :
Oce_Van_Mal_Nth_ESth_UWRA_Atchin_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Rano_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl
Oce_Van_Mal_Nth_ESth_UWRA_Uripiv_Dl

Check file numbers: any file prefixed with wl_16 is from this year and you will have transcription for it only at the end of April. 

In a way,
Oce_Van_Mal_Nth_WSth_Taute_Taute_Dl
is from this year, in that it was waiting until I had all the Toute recordings (planned for this round) done.  Of course, you couldn't have known that. I shouldn't have included it in last year's catalogue.

**Comment by LauraWae** [comment]
Uploaded the correct transcriptions of Oce_Van_Mal_East_SCtr_Nitita_Khatbol_Dl.

**Comment by LauraWae** [comment]
This is no treated in #367. I will close this issue now.
