### ISSUE TITLE
Progress Tracker: Marking up text grids for Celtic languages

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/Sound-Comparisons#322]

**Comment by PaulHeggarty** [comment]
### Languages Completed  [with date completed]
---------------------------------

**Comment by morenovuleta** [comment]
#Carbost is done and uploaded

**Comment by morenovuleta** [comment]
#Teelin is causing problems while loading in Praat; I keep getting error messages when trying to load it in different ways and when applying tiers to it - maybe 343 MB is so big it causes Praat to crash every time.

**Comment by cormacanderson** [comment]
There's something wrong there. It shouldn't be anywhere near that big. I'll look into it.

**Comment by PaulHeggarty** [comment]
Still in stereo?

**Comment by PaulHeggarty** [comment]
Moreno:  note the way to indicate a recording is done:  edit the [Languages Still to Mark Up] comment, to remove the language from the list there, and edit the [Languages Completed [with date completed]] comment, to paste that language into the list there, and note the date when it was completed.  I've just done the first one.  Please do others like this from now on.

**Comment by morenovuleta** [comment]
Done and marked-up
