### ISSUE TITLE
Pre-editing

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#327]
The first set of languages that went up were by definition "pre-edited" because it was I who cleaned them and marked them up for Praat. I realize now as Laura begins to mark up the larger sets that there is no question of my NOT pre-editing them. Speakers are simply not consistent in their realizations in the two samples, and choosing between them is not just a matter of identifying the cleanest -- we also want the one that is closest to what we can assume is the phonological representation, and I fear I am the only person who can judge that right now. Additionally, in a couple of cases, a speaker may switch between a basic and derived structure, or it may not be clear where a speaker has pulled back from a response -- that kind of thing. Again, only I, I fear, can judge that now.

I suggest that we leave the ones that are already up that I didn't pre-edit -- Mae-Bethel, Atchin, and Uripiv -- but we take them out of the transcription queue until I can double-check them and make any substitutions necessary -- i.e., until I get back. I don't actually expect that there will be many that need much post-pre-editing (generally, the clearer and stronger sample -- the natural pick -- is the first one, and it is the first one, too, that generally comes closest to the presumed phonological form). The Nahavaq, Avava, and Taute are all off the priority list for now anyway (for reasons I explain in my last post). I believe at least the Maraxus was done after I pre-edited it, so that would be a good one for Giovanni to start with. In any case, there is fun enough to be had for all with the files that I've been pre-editing over the past couple of days and that I am currently uploading as quickly as connection speed permits. 

So -- I'll restructure "3b" to make it clear which files are "go-aheads," which are "priority but on hold until Aviva double-checks," and which are "low priority." LAURA and I have already been emailing about this and we've decided that from here out she'll be marking up the pre-edited files first. These have been uploaded into "To Clean Up - Phase 1" are easy to identify because file names include dialect names and end in "_selected". 

LAURA: When you're done with those, I think they could go into the "go-ahead" section of 3b. You may have independent reasons for wanting to keep them out of that file, but as far as I'm concerned, anything I've pre-edited and you've cleaned is ready for Giovanni and is unproblematic content-wise for SC.

No pain!  There's been no wasted effort or doubling of work! All those files needed to be marked up, anyway. It will be time-consuming for me to rake through them, but it would have been time-consuming for me, too, to have pre-edited them. It's a toss-up.

**Comment by LauraWae** [comment]
Got that.

**Comment by LauraWae** [comment]
Hi @AvivaShimelman ,
I have one request. Giovanni has reported that the 52-words file of wl_0046_ Aingelemolesa_01 has a lot of errors. I would like to clean it up for the 215 words, so that he gets his samples completed.

1.) Can you preselect this file for all 215 words?

or 

2.) Shall I clean it up, following the first-word-policy, and you post-edit it?

or

3.) We wait until later because this is an old file? (which I would not prefer)

Best wishes,
Laura

**Comment by AvivaShimelman** [comment]
It's definitely better for me to clean it up, but, I regret, that's not at
the top of my list right now. Let's hold off on that file -- Giovanni has
enough to keep busy for now.

A.

On Sat, Apr 2, 2016 at 3:53 AM, LauraWae <notifications@github.com> wrote:

> Hi @AvivaShimelman <https://github.com/AvivaShimelman> ,
> I have one request. Giovanni has reported that the 52-words file of
> wl_0046_ Aingelemolesa_01 has a lot of errors. I would like to clean it up
> for the 215 words, so that he gets his samples completed.
>
> 1.) Can you preselect this file for all 215 words?
>
> or
>
> 2.) Shall I clean it up, following the first-word-policy, and you
> post-edit it?
>
> or
>
> 3.) We wait until later because this is an old file? (which I would not
> prefer)
>
> Best wishes,
> Laura
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/327#issuecomment-204468813>
>



-- 
Aviva Shimelman, PhD
