### ISSUE TITLE
File label changes

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#329]
RE: 2016 03 26 SC Malakula Revised file names:

Attached is a spreadsheet that identifies new file names.  

File numbers have not changed - wl_n1n2n3n4 is still wl_n1n2n3n4. 

File numbers were previously suffixed with language names and numbers counting recordings of that language. 

Example: wl_0026_Nahavaq_04.  

(Exception: in instances where the identification of a language was still a matter for analysis, "dialect" names were used in the label. Example: wl_0007_Salang_01).

(Aside - really, I should never have put any "meaningful" (human-oriented) material in the file names at all.  That "information" assumes an analysis that is still pending, an analysis, which, in any case, assumes a paradigm which is not universally accepted. Once a file has a unique label, any automated system knows what to do with it, and any human can retrieve "mnemonics" from the metadata. Labels that are relevant to a specific use of a file (i.e., Sound Comparisons) are necessarily independently assigned and may change, in which case human confusion is possible when "informative" file names now misinform). 

In general, this has not changed. Old file names have just been suffixed with dialect names. 

Example:

wl_0026_Nahavaq_04 

is now 

wl_0026_Nahavaq_04_Lembinwin

Language name has been changed only in the case of the "Letemboi" languages (Nevatanyene, Newoteyene, Natingatlang, and Aingelemolesa). In these cases, "Letemboi" now figures in the language slot and Nevatanyene, etc., now figure in the dialect slot. Example:

wl_0044_Newoteyene_01

is now

wl_0044_Letemboi_04_Newoteyene

Careful! Language/dialect PAIRS uniquely identify speech communities, they DO NOT uniquely name recordings. We may have multiple recordings from a single speech community -- Russell in fact wants this and in a later version of the site, he will want to have multiple voices representing the same speech community. Language/number/dialect TRIPLES DO uniquely name recordings (and, of course, recording numbers uniquely name recordings). This means that you must still look at the number. 

In the cases of Angavae, Salang, Fifti and Nitita, I have "repeated" language name as dialect name. These cases have in common (1) that the name of the dialect (equivalent in these cases to the name of the place where those languages are spoken) is not unique: other languages have the same dialect name (i.e., are spoken in the same place) and (2) that they have a single remaining dialect in any case.

PRACTICALITIES:

Who has to actually change what where, when?

![image](https://cloud.githubusercontent.com/assets/17926707/14068584/b3d0d41a-f4d3-11e5-9916-7f6709cd7104.png)

[2016 03 28 NEW SC Malakula revised file names.xlsx](https://github.com/lingdb/Sound-Comparisons/files/191216/2016.03.28.NEW.SC.Malakula.revised.file.names.xlsx)

**Comment by AvivaShimelman** [comment]
The attached file succeeds and replaces "2016 03 28 NEW SC Malakula revised file names.xlsx" attached to the original post.  It is different only in that it removes an extra space in the new file name for wl_0034
[2016 03 28 NEW 2 SC Malakula revised file names.xlsx](https://github.com/lingdb/Sound-Comparisons/files/191230/2016.03.28.NEW.2.SC.Malakula.revised.file.names.xlsx)

**Comment by PaulHeggarty** [comment]
Please use the assign function on any new issues, otherwise the assignee is not necessarily alerted to them.  I had not seen this until now.

**Comment by PaulHeggarty** [comment]
Have we got out of sync?  I updated this file on 28th too, using the latest version on OwnCloud, which had been dated to 20th until then.  We have to use OwnCloud for file sharing, not github.  It seems we now have two versions with the same date which both of us have worked on independently, and now our edits will have to be merged back into one file.

**Comment by PaulHeggarty** [comment]
My above comment may not be relevant.  I realise (think) now that you were referring to a different, separate file to the main Languages Reference file on OwnCloud.

**Comment by PaulHeggarty** [comment]
On this:
_We may have multiple recordings from a single speech community -- Russell in fact wants this and in a later version of the site, he will want to have multiple voices representing the same speech community._
I would in fact certainly advise Russell against this.  It will confuse far more than it will help anyone or any purpose, I think, other than pleasing the locals on the presumably rare occasions that they’d actually use the site.  I don’t think that counterbalances enough the many drawbacks I see with this.  Laura, I would say for now that this is absolutely, certainly, not a priority.  Please do edit multiple dialects of the same language, as you are doing.  But do *not* yet spend time on editing multiple speakers of the same dialect of the same language.  We have far bigger priorities for the Sound Comparisons project as a whole.  I am quite happy to have this discussion with Russell.

**Comment by AvivaShimelman** [comment]
Works for me.

On Wed, Mar 30, 2016 at 5:49 AM, Paul Heggarty <notifications@github.com>
wrote:

> On this:
> *We may have multiple recordings from a single speech community -- Russell
> in fact wants this and in a later version of the site, he will want to have
> multiple voices representing the same speech community.*
> I would in fact certainly advise Russell against this. It will confuse far
> more than it will help anyone or any purpose, I think, other than pleasing
> the locals on the presumably rare occasions that they’d actually use the
> site. I don’t think that counterbalances enough the many drawbacks I see
> with this. Laura, I would say for now that this is absolutely, certainly,
> not a priority. Please do edit multiple dialects of the same language, as
> you are doing. But do *not* yet spend time on editing multiple speakers
> of the same dialect of the same language. We have far bigger priorities for
> the Sound Comparisons project as a whole. I am quite happy to have this
> discussion with Russell.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/329#issuecomment-203045964>
>



-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment]
Closed while wincing at the misery we all went through because we didn't get this right three months ago!
