### ISSUE TITLE
Bislama pronunciations and spelling mismatches

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#330]
Very good to see that Bislama is up and working on the website.  No transcriptions yet -- are they going to be done, or just use spellings?  
The pronunciations of some words, though, seem closer to standard English than to the Bislama spelling:  three is pronounced with a θ not t, hand with a final -nd not just -n, and six without the second i of the spelling sikis.

**Comment by AvivaShimelman** [comment]
Bislama spelling -- to the degree it is standardized -- reflects the pronunciation of less educated speakers of 20 years ago.  Younger and more educated speakers will bring their production a little more in line with English norms -- especially when they're being extra-careful in a recording. In theory, Bislama doesn't have [ʃ] or [ʤ], but they're common now even in relaxed speech. Just let me know which you prefer -- spelling or transcription. There are, of course, arguments for both.

**Comment by PaulHeggarty** [comment]
This sounds, as expected, a bit like the observer's paradox problem, and that of a creole typically being a continuum of sociolinguistic registers, if the base language (English here) is still around and known.  My preference is clear:  record an older and less educated speaker who will give us closer to the "pronunciation of less educated speakers of 20 years ago".  NORMS or NORFS, or whatever they would be on Malakula.  Obviously, there's a case for having both that and a younger, more educated version like we already have.  We could put up both, no problem, but if anything I’d prefer the older, less educated.

**Comment by LauraWae** [comment]
As there are two Bislama varieties now on the web site and both have transcriptions, I will close this issue now.
