### ISSUE TITLE
Change URLs for 1 Language view to the Sound Comparisons Language FileName

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#339]
Current URLs for 1-Language view can look like this:
http://www.soundcomparisons.com/#/en/Romance/language/Gallo%3A Janz%C3%A9
Note that the automatic link on github fails, because there is a space within the URL.  You’ll have to cut and paste.  
It also looks very ugly, and people won’t be able to use or remember these reliably.

We need to move to spaceless, accentless names.  Especially important for the public short urls to cite.  

We already have such a language name:  it's the Sound Comparisons filename.  So please restructure things so that the URL is of this form instead:

http://www.soundcomparisons.com/#/en/Romance/language/Rce_Fr_Nth_Gallo_Janze_Dl

This will also save a bit of time for the Sound Comparisons team to work with the database and website together.

**Comment by Bibiko** [comment]
@PaulHeggarty please empty the caches of your browsers and try the new url scheme like http://www.soundcomparisons.com/#/en/Romance/language/Rce_Fr_Nth_Gallo_Janze_Dl

**Comment by Bibiko** [comment]
to avoid _special characters_ inside word URLs is not so straightforward - one should either add a new column which stores the unique ASCII-only version of a word (without spaces, apostrophes, etc.) or try to replace such characters on-the-fly by under_scores and look if the uniqueness still exists - but by my opinion the new column should be the safer way

**Comment by PaulHeggarty** [comment]
I love it!  Hallelujah!

**Comment by PaulHeggarty** [comment]
As for words, I agree it's safer to have a new column.  But in fact, we already have something like this, although we'd need to check whether it works fully.  This is because the sound files all have a component which is a URL-friendly version with no special characters, and which maps 1 to 1 (I hope!) onto words in each study.  So presumably we can use this URL form of the word names.  There are things I’d have to check first, though, because the word-name strings are unique also because they include digits from the Elicitation Index, e.g. 001_one.  And for legacy reasons they vary a bit between studies, sometimes using Spanish rather than English, or including an ancestral language form too.  I’ll have to look into this and get back to you.
But for now, that this already works for languages is a wondrous thing!

**Comment by PaulHeggarty** [comment]
Since you’ve just been working on this issue, worth considering these two other issues that are fairly closely-related, to judge whether it's best to do them now, while you’re fresh with this block of code.
- Make the language name page header in 1-Language table view a clickable search/filter box like in CoBL, so that users can just type language names into it and immediately get suggestions for matching languages.  I’m sure we had an issue for this, but I can’t find it!
- https://github.com/lingdb/Sound-Comparisons/issues/130   Not so urgent, but would be a nice synergy, because it would allow for automatic links from other databases (and wikipedia?) to Sound Comparisons.

**Comment by Bibiko** [comment]
@PaulHeggarty please empty the caches of your browsers and try the new url scheme for words like http://www.soundcomparisons.com/#/en/Celtic/word/in_head
