### ISSUE TITLE
German version of the site: some box titles of the Romance languages are mixed up in the left hand menu

### ISSUE THREAD

**Issue by LauraWae** [lingdb/Sound-Comparisons#340]
There are two boxes titled "Iberische Halbinsel". Actually, the second one should be titled "Frankreich". The third box is "Alpen", not "Frankreich". The third one should be called "Italien: Norden", and the fourth "Italien: Süden".

**Comment by LauraWae** [comment]
Solved this problem via translation tool.

**Comment by runjak** [comment]
Ah, that's nice to hear :)
