### ISSUE TITLE
Word page headings still show Longer from only

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#345]
They should show:
Short form  (longer form)
e.g. Celtic 'white' shows as 'Ir. fair-haired'.

**Comment by runjak** [comment]
Actually the long form should include the short form.
For Slavic we have 'green (masc. sg.)' as long form, and the same should apply for Celtic.

**Comment by PaulHeggarty** [comment]
So this was actually a data problem, not a programming problem, and it seems now to have been fixed in all cases.  There may be a few stragglers to pick up as and when we notice, but other than that this issue is closed.
