### ISSUE TITLE
Celtic:  Data Administration and Progress Tracker

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#346]
There were plenty of mismatches between older and newer versions of the English reference 'names' of about a dozen cognates in the Celtic list.  e.g. 'white' vs. 'fair-haired'.  All sound files should now have been correctly renamed, but where a lexeme was identified in a TextGrid according to the old name, if the Celtic_index file used the new name, that word would simply not have been identified by the script and the corresponding sound segment would not have been created as an individual word recording file.  So the scripts now need to be run again, on the TextGrid files attached here, which have been corrected to replace old cognate names with the correct new ones.

[Celtic to Correct.zip](https://github.com/lingdb/Sound-Comparisons/files/248208/Celtic.to.Correct.zip)

**Comment by PaulHeggarty** [comment]
Another correction still outstanding is to complete the correction of the 'longer form' word names in cases similar to this one.  This has to be done through the translation interface, using the English translation, and doing a search for all entries that include the string Br. and Bryth.  One for Cormac to do

**Comment by PaulHeggarty** [comment]
Laura, can you tell us which of these formats is needed now?  And run whichever is the right one!
[Index_Celtic (2).txt](https://github.com/lingdb/Sound-Comparisons/files/248536/Index_Celtic.2.txt)
[Index_Celtic.txt](https://github.com/lingdb/Sound-Comparisons/files/248524/Index_Celtic.txt)

**Comment by LauraWae** [comment]
Hi,
The languages which are lacking sound right now on the website are the following:
Dgl: Gweedore-Carrick
Dgl: Tory Island
Kyntire: Tarbert
Argyll: Taynuilt
Vann: Brech Skr. 2

**Comment by LauraWae** [comment]
I found that all of them except Vann: Brech Skr.2 are cleaned up and tagged in Owncloud Folder Celtic\3 - CA - To Check Mark Up. @cormacanderson

**Comment by LauraWae** [comment]
I found that all of them except Vann: Brech Skr.2 are cleaned up and tagged in Owncloud Folder Celtic\3 - CA - To Check Mark Up. (I hope Ihave  made no mistake in assigning the system names to the web site names @cormacanderson )
