### ISSUE TITLE
Spelling and transcription word filters are broken in Andean study

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#349]
- [x] Choosing `Ancestral Quechua` as the spelling language does not update the list of spellings to ancestral Quechua, they remain in English (as site language).
- [x] Choosing `Cuzco` as the phonetics language does update the list of transcriptions, but typing in the phonetics filter box has no effect, all words remain visible.

**Comment by runjak** [comment]
The reason for most of the spelling languages in the `Andean` study not displaying correct translations for words is in the database:
![screenshot_2016-05-25_12-09-39](https://cloud.githubusercontent.com/assets/5417642/15536466/a86308f2-2271-11e6-919f-ca729c740ab7.png)
Only for `Mapudungun` we have translations and these work as expected.

-----
I'll have a look at the phonetics filter box now.

**Comment by PaulHeggarty** [comment]
OK, I think I realise what happened.  At one stage we had to do a full delete and reload of all transcriptions, and the proto-languages did not get uploaded because they were originally from my Access database, and not in the Excel sheets used to create the new SQL statements to create the new records.  I will add them in now and upload new SQLs.

**Comment by PaulHeggarty** [comment]
Thanks Jakob, your diagnosis on point 1 is correct.  So far I've uploaded the SQLs for Ancestral Quechua and Ancestral Aymara, and they’re both working now.  Now to fix Quechua spelling and Chipaya...

**Comment by runjak** [comment]
Excellent :tada: 
I think I have a fix for the second point that I can deploy soon.

**Comment by runjak** [comment]
I've deployed the updated JavaScript code which fixed the problem in the cases I tried.
Once the cached files get updated this issue will fade for clients as well.

**Comment by PaulHeggarty** [comment]
Southern Quechua spelling and Chipaya are also now fixed in the database.  There are still some corrections to do to the Mapudungun reference language, which has some missing words, replaced by English.  So I'll re-open this issue but re-assign it to myself, since it's no longer a programming issue.

**Comment by PaulHeggarty** [comment]
On reflection, I'll close this issue with this title, and open a new one for the remaining problem for Mapudungung, which is just a data problem:
 Fix Mapudungun spelling entries: some are missing #353
