### ISSUE TITLE
Odd data to fix:  Malakula 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#352]
Sound does not correspond to the recording for:
http://www.soundcomparisons.com/#/en/Malakula/language/
Tirax%3A%20Olamb                     word: green

**Comment by PaulHeggarty** [comment]
Keep this issue open and add any other similar cases to the first comment box above -- not new comments.

**Comment by AvivaShimelman** [comment]
Hello!
It can be changed to [iɣasɣasan].

LAURA:

There's a little "breath sound" something like a half a second after the
the word. Maybe we should extend the silence around the word a little
further or cut the sound a little closer in.  For the same word, in Malua
Bay: Marasup. there's a little "scrape" sound, and in Nisvai, you hear the
cue "small."

I'm not going through them systematically yet -- just a couple of samples.

A.

On Wed, May 25, 2016 at 5:31 PM, Paul Heggarty <notifications@github.com>
wrote:

> Sound does not correspond to the recording for:
> http://www.soundcomparisons.com/#/en/Malakula/language/
> Tirax%3A%20Olamb word: green
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/352>
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
Thanks for opening this issue. This first one is now done. I am sure it will be very useful from now on for further improving the website.

**Comment by LauraWae** [comment]
I will close this issues. Odd Malakula data will be treated in #387.
