### ISSUE TITLE
Corrected system for default Lgs / Wds in Multi-Tables

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#358]
Currently, the default lgs and wds in the `Lgs x Wds` table and `Wds x Lgs` table are the same, and cannot be distinguished.  
In fact …
- the `Lgs x Wds` table can and should accommodate up to 20-30 languages, but not more than 5-10 words.
- the `Wds x Lgs` table can and should accommodate up to 20-30 words, but not more than 5-10 languages.

So the old csv table `DefaultTableMultipleLanguages.txt` has now been replaced by two tables, here are the first sample files for you to work on integrating.  It should be pretty fast, because the fields and their names are just the same.

[DefaultTableC30LgsForLgsXWdsTable.txt](https://github.com/lingdb/Sound-Comparisons/files/292223/DefaultTableC30LgsForLgsXWdsTable.txt)
[DefaultTableC05LgsForWdsXLgsTable.txt](https://github.com/lingdb/Sound-Comparisons/files/292224/DefaultTableC05LgsForWdsXLgsTable.txt)

**Comment by PaulHeggarty** [comment]
Later, we need to move to a similar differentiated system also for the Words in these two tables, but the priority is certainly the languages.

**Comment by runjak** [comment]
I doubt how fast this is going to be, but will certainly work to make it possible :)

**Comment by runjak** [comment]
What is the meaning of the `C05` and `C30` parts in the file names?
Is there a specific idea behind it or should I treat it as a `don't care` case?

**Comment by runjak** [comment]
Ok - I've got a working implementation for this.
The import will be fixed to the two filenames you provided,
so if you need other `C**`` parts in your file names I'll need to know about it.
I'll soon deploy the changes.

**Comment by PaulHeggarty** [comment]
The c05 and c30 just help me distinguish, because I keep mixing up Languages x Words and vice versa!  c 05 = circa 5 languages, which makes it clear that the languages are the columns in that version of the table.  When they are the rows of the table, we can tolerate up to about 30 of them.

**Comment by PaulHeggarty** [comment]
OK, while we're at this, and because I had time to kill listening to talks this afternoon, I’ve actually set things up for the *Words* axis of these tables too (as mentioned 'for later' in my second comment above).
This one turns out to be a bit more complicated, in that a separate sub-table has to be put out for each family, like with the normal words tables.  These should just be concatenated into the same table, I presume just as you already do.  You'll thus end up with two master tables called this:
- `DefaultTableC05WdsForLgsXWdsTable`
- `DefaultTableC30WdsForWdsXLgsTable`
… each concatenated out of the sets of tables with the study/family name suffixes such as _Andean

So here are the files you'll need to combine:

[DefaultTableC05WdsForLgsXWdsTable_Mapudungun.txt](https://github.com/lingdb/Sound-Comparisons/files/294287/DefaultTableC05WdsForLgsXWdsTable_Mapudungun.txt)
[DefaultTableC05WdsForLgsXWdsTable_Romance.txt](https://github.com/lingdb/Sound-Comparisons/files/294284/DefaultTableC05WdsForLgsXWdsTable_Romance.txt)
[DefaultTableC05WdsForLgsXWdsTable_Slavic.txt](https://github.com/lingdb/Sound-Comparisons/files/294288/DefaultTableC05WdsForLgsXWdsTable_Slavic.txt)
[DefaultTableC30WdsForWdsXLgsTable_Andean.txt](https://github.com/lingdb/Sound-Comparisons/files/294285/DefaultTableC30WdsForWdsXLgsTable_Andean.txt)
[DefaultTableC30WdsForWdsXLgsTable_Celtic.txt](https://github.com/lingdb/Sound-Comparisons/files/294286/DefaultTableC30WdsForWdsXLgsTable_Celtic.txt)
[DefaultTableC30WdsForWdsXLgsTable_Englishes.txt](https://github.com/lingdb/Sound-Comparisons/files/294289/DefaultTableC30WdsForWdsXLgsTable_Englishes.txt)
[DefaultTableC30WdsForWdsXLgsTable_Germanic.txt](https://github.com/lingdb/Sound-Comparisons/files/294290/DefaultTableC30WdsForWdsXLgsTable_Germanic.txt)
[DefaultTableC30WdsForWdsXLgsTable_Malakula.txt](https://github.com/lingdb/Sound-Comparisons/files/294291/DefaultTableC30WdsForWdsXLgsTable_Malakula.txt)

AND ...

[DefaultTableC30WdsForWdsXLgsTable_Mapudungun.txt](https://github.com/lingdb/Sound-Comparisons/files/294292/DefaultTableC30WdsForWdsXLgsTable_Mapudungun.txt)
[DefaultTableC30WdsForWdsXLgsTable_Romance.txt](https://github.com/lingdb/Sound-Comparisons/files/294293/DefaultTableC30WdsForWdsXLgsTable_Romance.txt)
[DefaultTableC30WdsForWdsXLgsTable_Slavic.txt](https://github.com/lingdb/Sound-Comparisons/files/294294/DefaultTableC30WdsForWdsXLgsTable_Slavic.txt)
[DefaultTableC05WdsForLgsXWdsTable_Andean.txt](https://github.com/lingdb/Sound-Comparisons/files/294295/DefaultTableC05WdsForLgsXWdsTable_Andean.txt)
[DefaultTableC05WdsForLgsXWdsTable_Celtic.txt](https://github.com/lingdb/Sound-Comparisons/files/294296/DefaultTableC05WdsForLgsXWdsTable_Celtic.txt)
[DefaultTableC05WdsForLgsXWdsTable_Englishes.txt](https://github.com/lingdb/Sound-Comparisons/files/294297/DefaultTableC05WdsForLgsXWdsTable_Englishes.txt)
[DefaultTableC05WdsForLgsXWdsTable_Germanic.txt](https://github.com/lingdb/Sound-Comparisons/files/294299/DefaultTableC05WdsForLgsXWdsTable_Germanic.txt)
[DefaultTableC05WdsForLgsXWdsTable_Malakula.txt](https://github.com/lingdb/Sound-Comparisons/files/294298/DefaultTableC05WdsForLgsXWdsTable_Malakula.txt)

**Comment by runjak** [comment]
The currently working code doesn't concat tables together at the moment.
The python rewrite did that but is currently not being worked on.
I'll make sure to start the tables for the files mentioned above in their concatenated form.
To not complicate the transition.

**Comment by runjak** [comment]
I see that the files you gave contain the columns
`"Study Ix","Family Ix","Ix Elicitation"`
whereas the `Default_Multiple_Words` up until now contained the columns
`"IxElicitation","IxMorphologicalInstance","StudyIx","FamilyIx"`
from this I infer that the `IxMorphologicalInstance` is no longer necessary for this purpose?

**Comment by runjak** [comment]
Looking at the current import code it appears that it would be simpler to add default tables per study rather than making bigger changes to the import code.

**Comment by PaulHeggarty** [comment]
Sorry, this is a mistake on my part.  I will correct the tables to include the same fields as before.
The import code should be pretty much copyable from what you already have for the Words table and others that vary by study, though, shouldn't it?

**Comment by PaulHeggarty** [comment]
If I knew how to concatenate tables in Access SQL syntax I would, but I can’t work it out!

**Comment by runjak** [comment]
Yes, the import code is quite flexible in some aspects.
It's just that it's easier to specify imports to several automatically inferred tables than to teach the import system to take part of the file name as a data for a specific column.
That's why I'll use different tables in this case - I don't expect it to hinder later merging of the tables.

**Comment by PaulHeggarty** [comment]
Actually, I’m a bit baffled, I thought that the `IxMorphologicalInstance` was *not* in the `Default_Multiple_Words` table.  I’ve checked the old copy I had in my database and that seems to have been the case.  
The point is that  `IxMorphologicalInstance` is 0 for all cases, I think.
Anyway, attached are the new files that do include that field, even if it's always 0 for now.

[DefaultTableC05WdsForLgsXWdsTable_Englishes.txt](https://github.com/lingdb/Sound-Comparisons/files/295047/DefaultTableC05WdsForLgsXWdsTable_Englishes.txt)
[DefaultTableC05WdsForLgsXWdsTable_Germanic.txt](https://github.com/lingdb/Sound-Comparisons/files/295045/DefaultTableC05WdsForLgsXWdsTable_Germanic.txt)
[DefaultTableC05WdsForLgsXWdsTable_Malakula.txt](https://github.com/lingdb/Sound-Comparisons/files/295044/DefaultTableC05WdsForLgsXWdsTable_Malakula.txt)
[DefaultTableC05WdsForLgsXWdsTable_Mapudungun.txt](https://github.com/lingdb/Sound-Comparisons/files/295048/DefaultTableC05WdsForLgsXWdsTable_Mapudungun.txt)
[DefaultTableC05WdsForLgsXWdsTable_Romance.txt](https://github.com/lingdb/Sound-Comparisons/files/295046/DefaultTableC05WdsForLgsXWdsTable_Romance.txt)
[DefaultTableC05WdsForLgsXWdsTable_Slavic.txt](https://github.com/lingdb/Sound-Comparisons/files/295049/DefaultTableC05WdsForLgsXWdsTable_Slavic.txt)
[DefaultTableC05WdsForLgsXWdsTable_Andean.txt](https://github.com/lingdb/Sound-Comparisons/files/295051/DefaultTableC05WdsForLgsXWdsTable_Andean.txt)
[DefaultTableC05WdsForLgsXWdsTable_Celtic.txt](https://github.com/lingdb/Sound-Comparisons/files/295050/DefaultTableC05WdsForLgsXWdsTable_Celtic.txt)

[DefaultTableC30WdsForWdsXLgsTable_Mapudungun.txt](https://github.com/lingdb/Sound-Comparisons/files/295052/DefaultTableC30WdsForWdsXLgsTable_Mapudungun.txt)
[DefaultTableC30WdsForWdsXLgsTable_Romance.txt](https://github.com/lingdb/Sound-Comparisons/files/295054/DefaultTableC30WdsForWdsXLgsTable_Romance.txt)
[DefaultTableC30WdsForWdsXLgsTable_Slavic.txt](https://github.com/lingdb/Sound-Comparisons/files/295053/DefaultTableC30WdsForWdsXLgsTable_Slavic.txt)
[DefaultTableC30WdsForWdsXLgsTable_Andean.txt](https://github.com/lingdb/Sound-Comparisons/files/295056/DefaultTableC30WdsForWdsXLgsTable_Andean.txt)
[DefaultTableC30WdsForWdsXLgsTable_Celtic.txt](https://github.com/lingdb/Sound-Comparisons/files/295055/DefaultTableC30WdsForWdsXLgsTable_Celtic.txt)
[DefaultTableC30WdsForWdsXLgsTable_Englishes.txt](https://github.com/lingdb/Sound-Comparisons/files/295057/DefaultTableC30WdsForWdsXLgsTable_Englishes.txt)
[DefaultTableC30WdsForWdsXLgsTable_Germanic.txt](https://github.com/lingdb/Sound-Comparisons/files/295058/DefaultTableC30WdsForWdsXLgsTable_Germanic.txt)
[DefaultTableC30WdsForWdsXLgsTable_Malakula.txt](https://github.com/lingdb/Sound-Comparisons/files/295059/DefaultTableC30WdsForWdsXLgsTable_Malakula.txt)

**Comment by PaulHeggarty** [comment]
Just for reference … maybe I should zip files like that, or is there a simple way you know of on github of downloading all of them in one go?

**Comment by runjak** [comment]
Yes - you are right - it appears that I've had the column in the database table but that it wasn't in the files you gave. This appears to be my mistake.
If the `IxMorphologicalInstance` column is indeed not necessary, I would opt to just ignore it in the imports and we could leave it out altogether?

I got some means to handle bunches of files together once they're on my machine. But I'm downloading them separately as long as they're not too many different ones. The current approach of exchanging files is ok for me unless you prefer a `.zip`.

**Comment by runjak** [comment]
Alright - I have an implementation for this.
I will deploy after a little bit of testing.

**Comment by PaulHeggarty** [comment]
Great.  Back to cobl 0th issues for now, then!

**Comment by runjak** [comment]
Deployed.
