### ISSUE TITLE
Set up Offline Version of SndComp website

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#362]
Ideally this should include:
- [x]  Map Caching -- perhaps best to do this together with switching to a new system for base-maps anyway.  See the other issues wIth label:"Offline Version" and label:"Website: Map".
- [x]  Easy ability to update, from github.

Target date to install on Russell's and Aviva's laptop is 21st June 2016.

Obviously, the more issues are fixed in time for the install, the better, but to be balanced by the urgency of some CoBL issues too.  I will now prioritise more highly and also tag with the `Offline Version` label any issue that really needs doing in time for the Offline Version for Malakula.

---

Todo as of 2016-06-24:
- [ ] Find a way to distribute the offline version of the site via network (FTP).

**Comment by runjak** [comment]
I can only deliver the ability to update from GitHub partially:
* The sound files and cached map parts are too big for a repository (OwnCloud would likely be a better source for these)
* I can only put the database parts on GitHub if you feel OK with them being accessible there as well.
That said what I can do is provide releases that allow to download a snapshot of the code as `.zip` and `.tar.gz` as the releases for [CoBL](https://github.com/lingdb/CoBL/releases) currently have. For CoBL I already use this when updating the server, and it would be easy to provide the same for SoundComparisons.

**Comment by runjak** [comment]
I've done some researching on the internet and found out that it should be pretty easy to get maps working offline once I've swapped from google maps to leaflet.js (currently working on).

**Comment by runjak** [comment]
I found a way to generate map tiles on my machine.
![screenshot_2016-06-17_13-27-10](https://cloud.githubusercontent.com/assets/5417642/16149181/502178d8-348f-11e6-86cc-38fde7d5afb7.png)

Using the [klokantech/tileserver-mapnik](https://hub.docker.com/r/klokantech/tileserver-mapnik/) docker image and information from [osm2vectortiles.org](http://osm2vectortiles.org/docs/serve-raster-tiles-docker/) it's an easy thing to generate .png images from the vector data of the map locally.
I'll now need to figure out how to extract the correct `.png` files from the renderer so that they can be distributed for offline usage.

**Comment by runjak** [comment]
I've got the map feature working offline, looking like this:
![screenshot_2016-06-17_15-33-30](https://cloud.githubusercontent.com/assets/5417642/16152187/e1a8a39c-34a0-11e6-99b9-6a213a855ff8.png)
The screenshot show the current maximum zoom level.
* I'll experiment with higher zoom levels at one point to see how storage space and generation time grows.
* Clustering and a bit more fancy for the markers (rounded corners, highlighting when playing) will come back next.
* I think with this state we at least have something that works offline and has a map.

**Comment by AvivaShimelman** [comment]
Very exciting!

On Fri, Jun 17, 2016 at 3:35 PM, Jakob Runge <notifications@github.com>
wrote:

> I've got the map feature working offline, looking like this:
> [image: screenshot_2016-06-17_15-33-30]
> <https://cloud.githubusercontent.com/assets/5417642/16152187/e1a8a39c-34a0-11e6-99b9-6a213a855ff8.png>
> The screenshot show the current maximum zoom level.
>
>    - I'll experiment with higher zoom levels at one point to see how
>    storage space and generation time grows.
>    - Clustering and a bit more fancy for the markers (rounded corners,
>    highlighting when playing) will come back next.
>    - I think with this state we at least have something that works
>    offline and has a map.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/362#issuecomment-226770216>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM-7EDga1UDQGq4erOvCD1dx7sv1hks5qMqKqgaJpZM4IxB4H>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by PaulHeggarty** [comment]
Looking good.  And although I wouldn't normally choose this fairly plain political map as a default background, I hope it will still be available as one of the new choices of map background, because the great thing about this one is how clear the regional boundaries are within the countries shown, like Spain and France here.  That is one of the much commented spectacularly bad features of Google maps, the borders like this are almost invisible.  But when you’re working with 'regional languages' and 'dialects', these borders are crucial.  So please make sure this is available as one of the map options, even if it might not be the default one we go for.

**Comment by runjak** [comment]
I have found a [selection](https://leaflet-extras.github.io/leaflet-providers/preview/) of map tiles that is also used in wals.
We would perhaps need to decide on the layers we want to have.
I'll also have a look at the specific map @PaulHeggarty suggested.

**Comment by runjak** [comment]
Ok - so concerning the [maps-for-free](http://maps-for-free.com/) relief material:
We can use the map tiles because they are under [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license. Certainly attribution would be fair, but this is already taken care of for other maps so it shouldn't be problematic to get this done.

I'll need to investigate how best to include the tiles.

**Comment by PaulHeggarty** [comment]
At a first look over, these are ones I'd like to include:

Esri.NatGeoWorldMap
Esri.WorldImagery
Esri.WorldShadedRelief
Esri.DeLorme
Esri.WorldTopoMap

**Comment by runjak** [comment]
Just found out that we cannot use the Esri data offline.
From their [terms and conditions](https://developers.arcgis.com/terms/):
![screenshot_2016-06-21_11-10-29](https://cloud.githubusercontent.com/assets/5417642/16224094/db58a228-37a0-11e6-9c98-de40b1cee0f5.png)

**Comment by runjak** [comment]
I've updated the online version of soundcomparisons.
It's now running with leaflet.js :tada:

**Comment by runjak** [comment]
I'll be meeting with Russel tomorrow to give him a copy of the offline version.
I'm planning to copy the data this evening. It may still be possible to do something tomorrow before 11:00 but I'll get a copy ready today. Are there still urgend changes for:
* Database entries
* Contributor Photos
* Sound files

happening today/tomorrow?

**Comment by runjak** [comment]
* I've given a copy of the site to Russel :)
* The other USB sticks are filled with the same copies and it would probably make sense for me to leave these at the institute for @AvivaShimelman.
* It appears that owncloud doesn't like files as large as the site export.
![screenshot_2016-06-24_11-33-45](https://cloud.githubusercontent.com/assets/5417642/16334194/d14eed3a-39ff-11e6-855c-76776a25635d.png) so we'll probably need a different distribution vector for future versions.

**Comment by runjak** [comment]
I've just spoken with the IT about means to distribute large files.
There will be an FTP server available in the future that can be used for this.
Currently the only option to make data of this size available would be the server we use for the soundcomparisons website but disk space could really turn into a problem if I upload 1 or 2 archives. I'll reduce the priority for this issue and come back to it later.
