### ISSUE TITLE
Drop colours from transcription boxes on Malakula map

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#364]
The classification of languages into subsets is a big problem for Malakula.  It's just better to drop the colour system from the transcription boxes on Malakula map.  For all languages in Malakula (not any other studies, sorry, this has to be Malakula-specific!) they should appear only in the light green colour that is currently the colour of 'East' in this screenshot.
![screenshot - 10_06_2016 13_44_40](https://cloud.githubusercontent.com/assets/8819910/15963388/d83986d0-2f11-11e6-91d8-9687695a7cbf.png)

Preferably, this should only affect the transcription boxes.  The header bars for each language set, in the left-hand language selector column, should keep their colours.  I know, it's inconsistent and not very German, but it's what we need for now.  Eventually we should probably choose a colour for the transcription boxes that is not the same as any of the region headers...

**Comment by runjak** [comment]
Ok - I'll see to adjust things for this now.

**Comment by runjak** [comment]
I agree that this is not very [Stackenblochen](https://www.youtube.com/watch?v=d6wd78jMHDk), but I have a solution that looks like this:
![screenshot_2016-06-10_14-44-06](https://cloud.githubusercontent.com/assets/5417642/15964655/cdddd44a-2f19-11e6-90fb-2262548534ff.png)
I'll close this issue after deployment.
