### ISSUE TITLE
A-Z order is not working again 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#365]
We had this problem before, and I can’t remember what the fix was, but it's back on Malakula...  Setting the sort to A-Z doesn’t work in English even...
![screenshot - 12_06_2016 20_11_03](https://cloud.githubusercontent.com/assets/8819910/15993049/8022b3ba-30db-11e6-9b85-aca0b96d8f1c.png)

**Comment by runjak** [comment]
By calling `App.wordCollection.map(function(w){return w.getModernName();});` in the browser I was able to verify that the words themself appear to be sorted correctly, but the rendering appears to be problematic. I'm investigating how this comes to pass.

**Comment by runjak** [comment]
Found the bug and will close this issue on deployment.
