### ISSUE TITLE
Changing site language can choose wrong default phonetics filter language

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#371]
When a user changes the spelling filter language, the phonetics filter language will automatically change to the 'phonetic' filter language that corresponds to that spelling filter language.  So in Romance, if one changes the spelling filter language to Italian, the phonetics filter language automatically changes to `Std Italian: Romagna`.  This is exactly right.

However, when one changes site language, that triggers a change in the spelling filter language, if appropriate, but that event does not then trigger the automatic change to the corresponding phonetics filter language.  

Below is the screenshot after changing from site language English to site language Italian, which correctly set the spelling filter language to Italian, but did not change the phonetics filter language to `Std Italian: Romagna` as it normally would have done.  It has left it on the default language for 1-Language Table view, i.e. `Prov. Alp. Valdese` (to use its Italian name).

![screenshot - 15_06_2016 17_17_48](https://cloud.githubusercontent.com/assets/8819910/16085702/2f8c4c74-331d-11e6-9895-c06d03d48b54.png)

**Comment by runjak** [comment]
Ah, interesting issue.
