### ISSUE TITLE
Bugs in the Italian version

### ISSUE THREAD

**Issue by GAbete** [lingdb/Sound-Comparisons#375]
- [x] The Italian translations for “Show/Hide languages selector.” and “Show/Hide words selector.” are not displayed on the website.

- [ ] When I switch to Italian from another language, the Italian translations are not correctly loaded. One needs to refresh the page to visualize them correctly.

**Comment by runjak** [comment]
I believe the `Show/Hide` functionality has already been addressed in #368 and should be fixed by now. You may need to clear your browsers cache for changes to propagate.

**Comment by runjak** [comment]
I have a bit of trouble reproducing the translation problem with Italian.
Can you check if this is still a problem and provide the URL or a screenshot of the problem here to help me see this?

**Comment by GAbete** [comment]
You are right. I had to clear my browser cache. Both the problems have been solved now

**Comment by runjak** [comment]
Nice :)
I think it would be desirable for me to solve the caching issue in the future
- but for now it's what we got.
