### ISSUE TITLE
Files not appearing or not playing on SC

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#377]
I am sure this is just an issue with my not understanding the internal structure of SC, but it looks to me like we have two "funky" things going on:

First, there are languages that do appear on the reference sheet and that haven't -- to my knowledge -- been "turned off" but which nevertheless do not appear in the sidebar:
Aulua: Loxse-Asolokh, 
Vao: Beteehul
Venen Taute: Hamax

Second, there are languages that have been marked up (i.e., they appear in "to transcribe - marked up all 215", or, in a couple of cases in "-marked up 52") and for which I definitely supplied transcriptions (even updated transcriptions), yet they appear to be missing sound on the site (they "don't play"):

1. Njav (Siviti): Jericho
2. Venen Taute: Unmet, 
3. Nese: Tanmial (Labeled Nese: Matanvat in "to transcribe": file name Nese:MatanvatTanmial), 
4. Espiegel's Bay: Solwota (Labeled Malua Bay: Espiegel's Bay in "to transcribe"), 
5. Malua Bay: Tiptir, 
6. Tirax: Mae (at one time known as Tirax:MaeBethel), 
7. Nasarian: Wileven (currently only 52 -- but now pre-edited for 215), 
8. Angavae: Dixon Reef (currently only 52 -- but next on list for 215), 
9. Nitita: Khatbol 
10. Port Sandwich: Lamap, 
11. Port Sandwich: Merivar, 
12. Nombotkote: Blacksands, 
13.Nombotkote: Melkin
14. Burmbar: Burmbar
15. Wala: Small Island

Part of the problem for the ones that got relabeled might be a mismatch somewhere between scripts that ask for one file and no file by that name is returned. 

A.

**Comment by AvivaShimelman** [comment]
There are two left that were registering "soon" but should have transcriptions -- Tirax Botmelesnial and Venen Taute Hamax.  These languages also do not appear in the drop-down box on the right. I'm assuming that is because they don't have entries for any words. If that is not the case, i.e., if they should appear in any case, that might be an issue for Paul.

**Comment by LauraWae** [comment]
I think most of those aspects have been treated or can be treated in the future in #350. I will close this issue now.
