### ISSUE TITLE
Status of "Operation get offline version ready for Russell"

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#378]
This just makes explicit much of what I wrote last Sunday and the Friday 9 days before that, updated to account for my week's minor progress and Laura's somewhat better progress. From my point of view (i.e., just with regard to stocking the site, of course, and not making it run), the following things are still "out" and should be "in" by this Wednesday:

**For @Aviva**:

Pre-edit:

From current stock of 52's:

Angavae - 
Salang - 
Tape -

From last year's "unpublished" stock:

Novol (5 - Soasang)
Nombotkote (Melkin - 47)
Letemboi (Aingelamolesa or Nevatanyene)
Ninde (Windua)

And, time permitting (Don't worry, Laura, it surely won't!):

Nahavaq: Lembinwin
Bangaasak: Taremb

Transcribe/find transcription, respectively for:

Novol: Tavendrua
Tirax: Orap

Double-check transcriptions for the 10 languages already on the site that will remain 52s for now (listed below)
Double-check transcriptions for 3 languages that were published without pre-editing

Avava: Tembibi
Nombotkote: Blacksands
Nahavaq: Benaur

**For @Laura**:

Find missing files that were/were likely already marked up:

- [x] Alavas: AlavasWowo 

- [x] Atchin: Lilrang (in "done" but no corresponding marked up file to be found)

Clean and mark up:

The top eight (agreed-to "priority") files Aviva will be marking up (listed above)
The five files currently waiting in "to be cleaned up" (external ("first level") files only for now)
Nasarian_Wileven
Neverver_Mindu
Unua_Noferai
Pangkumu_Datisman
Vao_Beteehul

(I'm assuming Nitita: Khatbol is in that folder by mistake, as you put in a recent progress report that it had been cleaned up)

(The 13 currently pre-edited and waiting in "don't worry about for now" can be taken on at a less phrenetic pace after Russell leaves.

btw, the first priorities when you do get to these are:
Venen Taute: Hamax
Aulua: Lorxse-Lanfitfit).

The 7 that will necessarily remain for the moment in purgatory (52) are (in order of likely promotion):
Pangkumu: Ndarmif
Unua: Mbatumbo
Tesmbol: Melaklak
Letemboi (1 - probably Aingelamolesa)
Avava: Khatbol
Ninde: Opmobamba
Nahavaq: Caroline Bay

The following three could potentially escape in this round, in that we do have files from these languages already pre-edited (and in one case marked up) and transcribed but which I never catalogued because I didn't think I'd get them done. That said, they won't spoil and can certainly wait for the next round of cataloguing in the fall:

Nombotkote: Melkin
Neve'ei: Nefe'ei
Nombotkote: Melkin

New files also in this category are
Atchin: Lilrang

That's it, I think for now.
Time-wise, that cashes out to:
20-22 hours of on-task time (i.e., continuous work time) for Aviva over 3 days
22-24 hours of on-task time (i.e., continuous work time) for Laura (not including file-finding time) over four days (HEADS UP! That cashes out to an average of 6 hours a day! We both have to get on it.)

A.

**Comment by LauraWae** [comment]
**Atchin: Lilrang**:
We have no such entry on the reference sheet. However, we do have one cleaned up file and a text grid that are called "wl_160027_Atchin_03_Lilrang". It is the same recording as Oce_Van_Mal_Nth_ESth_UWRA_AtchinSmallIsland_Dl, which is already cleaned up on Owncloud.

We do have on the reference sheet an entry for "wl_160027_Atchin_03_SmallIsland". It is assigned to Oce_Van_Mal_Nth_ESth_UWRA_AtchinSmallIsland_Dl.

Are we treating with two different recordings ("Atchin: Lilrang" and "Atchin: Small Island")? If yes, we need another entry on the reference sheet,  i.e. in the database.
Thanks.

**Comment by AvivaShimelman** [comment]
Yupppee! Mystery solved. It looks like we have two Atchin files (as we
should) - 19 and 27. 19 got ingested as Orap and 27 ("Lilrang") as
SmallIsland. As it should be.

A.

On Mon, Jun 20, 2016 at 11:02 AM, LauraWae <notifications@github.com> wrote:

> *Atchin: Lilrang*:
> We have no such entry on the reference sheet. However, we do have one
> cleaned up file and a text grid that are called
> "wl_160027_Atchin_03_Lilrang". It is the same recording as
> Oce_Van_Mal_Nth_ESth_UWRA_AtchinSmallIsland_Dl, which is already cleaned up
> on Owncloud.
>
> We do have on the reference sheet an entry for
> "wl_160027_Atchin_03_SmallIsland". It is assigned to
> Oce_Van_Mal_Nth_ESth_UWRA_AtchinSmallIsland_Dl.
>
> Are we treating with two different recordings ("Atchin: Lilrang" and
> "Atchin: Small Island")? If yes, we need another entry on the reference
> sheet, i.e. in the database.
> Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/378#issuecomment-227087279>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKMwoSRLC1eVikQwDPHrnWUWhtKH7Aks5qNlcPgaJpZM4I47gS>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
Checked on the Reference Sheet: confirmed :)

**Comment by LauraWae** [comment]
Hi again.
Sorry, I am not quite sure how to understand those lines:
"Clean and mark up:

The top eight (agreed-to "priority") files Aviva will be marking up (listed above)
The five files currently waiting in "to be cleaned up" (external ("first level") files only for now)
Nasarian_Wileven
Neverver_Mindu
Unua_Noferai
Pangkumu_Datisman
Vao_Beteehul"

Which eight files do you mean? Or should I stick just to the list in the "malakula Progress Tracker"-issue (maybe you can add and switch the files according to the priority in this list if there are any changes?)?

**Comment by AvivaShimelman** [comment]
​Absolutely no changes have been made! That was all just a re-cap. Files
will magically appear in "to be cleaned up" Those files will be all and
only the files we originally agreed to.

:)​

On Mon, Jun 20, 2016 at 1:09 PM, LauraWae <notifications@github.com> wrote:

> Hi again.
> Sorry, I am not quite sure how to understand those lines:
> "Clean and mark up:
>
> The top eight (agreed-to "priority") files Aviva will be marking up
> (listed above)
> The five files currently waiting in "to be cleaned up" (external ("first
> level") files only for now)
> Nasarian_Wileven
> Neverver_Mindu
> Unua_Noferai
> Pangkumu_Datisman
> Vao_Beteehul"
>
> Which eight files do you mean? Or should I stick just to the list in the
> "malakula Progress Tracker"-issue (maybe you can add and switch the files
> according to the priority in this list if there are any changes?)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/378#issuecomment-227113974>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM6u4qctl1cdynxHY47ckPM05FeETks5qNnTzgaJpZM4I47gS>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
Ok! Good! :)

**Comment by LauraWae** [comment]
There are 13 languages that aren't playing on the site, but that I think should be.  They're all languages that you have already marked up and that we do have transcriptions for:  

- [ ] 1. Njav (Siviti) Jericho
- [ ] 2. Venen Taute: Unmet, 
- [ ] 3. Nese: Tanmial (Labeled Nese: Matanvat in "to transcribe"), 
- [ ] 4. Espiegel's Bay: Solwota (Labeled Malua Bay: Espiegel's Bay in "to transcribe"), 
- [ ] 5. Malua Bay: Tiptir, 
- [ ] 6. Tirax: Mae, 
- [ ] 7. Nasarian: Wileven (currently only 52), 
- [ ] 8. Angavae: Dixon Reef (currently only 52), 
- [ ] 9. Nitita: Khatbol (currently 52)
- [ ] 10. Port Sandwich: Lamap, 
- [ ] 11. Port Sandwich: Merivar, 
- [ ] 12. Nombotkote: Blacksands, 
- [ ] 13. Nombotkote: Melkin

In some cases (3, 4, 6, 10, and 11) part of the problem could be file names.  (3) and (4) have the two names indicated above; Tirax: Mae was formerly Tirax: MaeBethel; and (10) and (11) are the two Port Sandwich/Lamap short names that we just changed.

**Comment by AvivaShimelman** [comment]
"Closed" is such a nice word. Go play in the sunshine!
I'm going to be correcting transcriptions (again, still) tonight, so please
just set aside a half hour tomorrow morning to upload them.
A.

On Thu, Jun 23, 2016 at 3:57 PM, LauraWae <notifications@github.com> wrote:

> Closed #378 <https://github.com/lingdb/Sound-Comparisons/issues/378>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/378#event-701919662>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKMx1Chk21z3zPg1OI8Xgx45W5tZl7ks5qOpDUgaJpZM4I47gS>
> .
>



-- 
Aviva Shimelman, PhD
