### ISSUE TITLE
Posting revised transcriptions

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#379]
Hi, Laura,

I've been checking some of the transcriptions on the website, and it seems that a bunch of the revised transcriptions (not just those from recent days, but, indeed, those dated 05/29) are not showing up. I don't know if that means that they didn't get uploaded or if there is some kind of "apply" box that didn't get clicked or if it's something else. I would appreciate it so much if you could make it your first priority when you get back to working on SC. I think it is very important that we get the transcriptions right. It reflects badly on SC (and is a very big embarrassment for me) to have mistakes in the transcriptions. I'm going to integrate all the transcriptions I ever revised into a single sheet now, and I'll upload that to oc. Thanks so much!

Aviva

**Comment by AvivaShimelman** [comment]
I'm pasting the revisions that update the transcriptions in the current sheets on oc. I'm labeling them with today's date and, of course, leaving the current ones with their current date.

**Comment by AvivaShimelman** [comment]
I've been trying to reconcile the transcription sheets on oc, the revisions that I've uploaded, and the revisions that are showing up on the website, and, honestly, it is making my eyes swim.  Laura, you know what's been done and what hasn't, so I'm afraid I'll have to depend on you to enter anything that might not have gotten entered yet and check if there's any kind of glitch in uploading. I really regret handing off this task to you, but, really, I think, again, because only you know what has happened and what hasn't, it will be much, much faster for you than it has been for me. Sorry and thanks.  A.

**Comment by LauraWae** [comment]
Hi,
I am on it right now!
Cheers,
Laura

**Comment by LauraWae** [comment]
Done.

**Comment by AvivaShimelman** [comment]
Thanks!

On Mon, Jun 20, 2016 at 11:55 AM, LauraWae <notifications@github.com> wrote:

> Done.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/379#issuecomment-227099271>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM0K1WL4-XzbFDKEOsStDkR29LOKLks5qNmOSgaJpZM4I5Pip>
> .
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
Done.

**Comment by AvivaShimelman** [comment]
Thank you!

On Tue, Jun 21, 2016 at 12:15 PM, LauraWae <notifications@github.com> wrote:

> Done.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/379#issuecomment-227398484>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKMwlLmzAWtpZkOwETCU5oYOq2wcqZks5qN7mxgaJpZM4I5Pip>
> .
>



-- 
Aviva Shimelman, PhD
