### ISSUE TITLE
Make sure the soundfile folders on the server do not contain any full master recording files

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#381]
The full website structure is now to be made available offline, on the laptops of various people in the department, including Russell and Aviva, who will need to be able to demo Sound Comparisons when on Malakula island itself, without internet access.

This include copying all the sound file folders (at least for Malakula) onto their hard drives.  That needs a lot of space.  Previously, it was the case that copies of the full master .wav sound file was sometimes left in the sound files folder for a language, alongside all the individual word by word files.  That means huge amounts of space taken up on the hard drive, however.

So … it is very urgent to do some housekeeping on the sound file folders on the server, to search for and find any files (.wav or .mp3) that are master files, and should not be there.  Obviously, they should *not* simply be deleted, they need to be *moved* to the archive.

Please run a search for files whose size is greater than 200 kb (or some figure like that).  That should  identify all of the master files, but none of the individual word by word files, because they are presumably all smaller than 200 kb.

Any .zip files also inadvertently left on the server sound file folder structure should also be taken off there and put into an archive instead.

This is extremely high priority, because we want to copy over the file structure tomorrow, Tuesday 21st June.

**Comment by LauraWae** [comment]
- Mpg_Chl_Rgn8_Tirua_Tranicura_1035_toser.wav (1759 kb): this was a long answer. Cut and re-uploaded.

**Comment by PaulHeggarty** [comment]
Could you check and note down here how many GB the full sound file folder structure comes to in total?

**Comment by LauraWae** [comment]
It's 9.235 MB.
