### ISSUE TITLE
Set preferences for new map system

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#382]
The new map system, including storable maps offline, is superb.  A big desideratum ever since the start of the Sound Comparisons project, and this is great!  Many of the map views also seem to load much faster than Google maps used to, when zooming in, for example.

Nonetheless, here are some tweaks I would like to see, please:

- [x] Set default map view to Esri World Imagery
- [x] Delete option Stamen Watercolour.
- [x] Delete option Stamen Toner.
- [x] Change the order of the options (and make their names a bit friendlier with some spaces where appropriate) to this:
Esri World Imagery  [= default]
Esri NatGeo World Map
Open Street Map
Esri World Topo Map
Esri De Lorme
Esri World Shaded Relief
Google Maps
Google Earth
 
- [x] If possible, when the user tries to zoom to beyond the resolution available for the map type he is on, show a notice:  "For more detailed map resolution, switch map view to Esri World Imagery, Open Street Map, or Google Maps."
- [x] If possible, force reload over users' caches, because at the moment without a cache clear, users get this result:
![screenshot - 2016-06-21 21_04_52](https://cloud.githubusercontent.com/assets/8819910/16242701/fed7dd42-37f3-11e6-9e7b-d4733aab9e0a.png)

- [x] Get the transcription/sound play bubbles back to being rounded again, and avoid the problem where there are two entries in a bubble, but the second appears outside the bubble, even though the bubble is made bigger height-wise.  See this image:
![screenshot - 2016-06-22 15_13_10](https://cloud.githubusercontent.com/assets/8819910/16267874/4158e2fe-388c-11e6-8406-3e18bf6c21b7.png)

- [x] In 1-Language all words view, under the language name there appears a Google map place icon, which when clicked takes users to another tab with the Google map for that place.  I think we should probably switch this to OpenStreetMap instead by now.  And therefore use their icon rather than the Google placemarker icon.

**Comment by runjak** [comment]
I've identified and removed a problem that was linked to the caching problematic.
I'm not sure that it solves the caching, but it's an improvement nonetheless.

**Comment by PaulHeggarty** [comment]
I see you’re already progressing fast on this, good stuff!  Obviously, if there are individual issues like bringing back Google that might take various hours, then use your best judgement on prioritising how which to do in this issue, and which other ones to do first, to get the best overall improvement in time for Friday.  You probably won’t manage everything on the 0 list by then, I suppose, so go for the quick ones that give a big improvement.

**Comment by runjak** [comment]
I've found a [snippet](https://stackoverflow.com/q/11532636/448591) that could make it possible to get rid of the caching issue on the server.

**Comment by runjak** [comment]
Because of the license situation for google maps it appears to be a bit involved but still possible to get tiles from google maps displayed on our map.
Screenshot from the leaflet [FAQ](https://github.com/Leaflet/Leaflet/blob/master/FAQ.md):
![screenshot_2016-06-23_13-54-44](https://cloud.githubusercontent.com/assets/5417642/16302214/2d32dcf8-394a-11e6-9a0f-be5a601299d8.png)

I think I'd need a bit more time to figure out how the [plugin](https://github.com/shramov/leaflet-plugins) that enables google maps works.

**Comment by runjak** [comment]
Caching is now tracked as a separate issue in #391.
Therefore I'm ticking it off the list.

**Comment by runjak** [comment]
I've got an implementation for the rounded markers:
![screenshot_2016-09-09_12-54-43](https://cloud.githubusercontent.com/assets/5417642/18384766/ced71dc4-768c-11e6-9648-c83bfb4518e2.png)

**Comment by PaulHeggarty** [comment]
I like it!  Does it still do the 'oversize' boxes first, that then shrink, as it currently does?  Or is that part of the fix?

**Comment by runjak** [comment]
I expect the two points about bringing back `Google Maps` to be a larger issue that may be more complicated:
* As far as I understand we're not easily permitted to use the Google Maps tiles without the maps source code.
* Using the source code would imply that we need to have a system that deals with two partially different kinds of map logic.

I'm not confident that this would be fast to do or a small change/adjustment.
Therefore I've separated the maps part into #400.

**Comment by runjak** [comment]
I haven't experienced the `oversized boxes` problem in a while.
I think that would be part of the logic that clusters several markers into one.
The cluster logic is currently not implemented/finished as far as I know.

**Comment by runjak** [comment]
I found no way to implement a message with leaflet.js that would make it possible to notify clients when they've reached max zoom.
Since the default layer already allows for the possible maximum zoom to be used I would assume that users that are smart enough to discover the map layers are also smart enough to discover their differences if they need to.
That being said I will close this issue on deployment of the code for rounded map markers.

**Comment by runjak** [comment]
I've deployed the latest changes for this issue on the server.
Closing, because nothing else to do.
