### ISSUE TITLE
Rano Potoro and Chinambong - doubled and mismatched with transcriptions?

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#385]
At least in the offline version (online version not loading now), it seems like Rano Chinambong and Rano Potoro are using the same recording -- both Chinambong -- and the same transcription -- both Potoro. It is possible that the same recording got cleaned up twice -- it sounds to me like the intonation on 'woman' is different. Laura, could you double-check this? Let me know what you need me to do.

**Comment by LauraWae** [comment]
Hi, yes. It is the same speaker. Could you please upload a selected version again of Rano Potoro? The transcriptions are not the same, but very similar (at least not in the online version which works for me). Please check if you want other transcriptions to be uploaded and tell me:).

**Comment by AvivaShimelman** [comment]
I just uploaded it. It is far more of a priority right now for me to get
the other files done, though. i.e., re-doing that one is lower priority as
far as I'm concerned than is cleaning up any of the others in "to clean up"
(which, if you can, it would be great to have by the end of the day on
Thursday, because Jakob has to install the off-line version on Russell-s
computer on Friday morning). In the meantime, would it be possible to just
remove the sound from Potora? (i.e., it would be better to have no sound
play on the website than to have the wrong sound)).

Indeed, the transcriptions are different (which means I'm missing a schwa
in one of them!). Thanks!

On Wed, Jun 22, 2016 at 5:03 PM, LauraWae <notifications@github.com> wrote:

> Hi, yes. It is the same speaker. Could you please upload a selected
> version again of Rano Potoro? The transcriptions are not the same, but very
> similar (at least not in the online version which works for me). Please
> check if you want other transcriptions to be uploaded and tell me:).
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/385#issuecomment-227773050>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM89OYTERnb95Kbg9AKSfeq4zJ5WSks5qOU7YgaJpZM4I7mf->
> .
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
I have deleted the sound from Potora now. Thanks for finding that out.

**Comment by AvivaShimelman** [comment]
Thanks!

On Wed, Jun 22, 2016 at 5:42 PM, LauraWae <notifications@github.com> wrote:

> I have deleted the sound from Potora now. Thanks for finding that out.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/385#issuecomment-227785565>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARGKM5l7g7uHTjezgJmKUg_-D6VGsMefks5qOVf3gaJpZM4I7mf->
> .
>



-- 
Aviva Shimelman, PhD
