### ISSUE TITLE
Clicking on any unfold meaning set icon forces a full site reload

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#389]
When I click on any of the >-shaped unfold icons, e.g. the one next to 'Numbers' or 'Colours'  in this image, the whole website reloads and goes back to the 'loading bar' view.
![screenshot - 2016-06-23 14_03_13](https://cloud.githubusercontent.com/assets/8819910/16302408/4680fb76-394b-11e6-8abd-8c8cd19dd005.png)

The resulting page also unfolds all meaning sets, not just the one clicked. And it does not fold them back up when it should.
The page it tries to load is: 
http://www.soundcomparisons.com/#/href=
The language set unfold icons work fine, so perhaps look at the code for them?

**Comment by runjak** [comment]
Yes, I can reproduce this. Searching a fix rn.
