### ISSUE TITLE
Rechecking the map zoom every second has to be turned off

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#390]
If the user actually wants to use the map zoom, to focus on a particular region, within a second or so the command gets overridden and zooms straight back out.  
I’m afraid we'll have to go back to event triggers, not just checking every second, and try to keep catching all the triggers:  window resizing, hiding/showing selector columns. That should be it, surely?

**Comment by runjak** [comment]
Ah, I see that I didn't think this trough completely.
It should be possible to make two tasks of the code that zooms to a default level and the code that resizes the map. This would be a logical distinction anyway.
