### ISSUE TITLE
Fix caching

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#391]
Caching is a problematic thing in our application.
Since all site parts are loaded into the browser they survive page refreshes which leads to unexpected bugs experienced by only some users. These bugs are especially hard to reproduce. To fix this the following steps would make sense:
- [x] Prevent caching of `.js` files in the browser
- [x] Instead of storing template data in the `sessionStorage` it would make sense to either prevent caching for the templates or inject them into the `.js`.
  The latter could also reduce load times and is therefore preferred.

---

Original content:

No response on click, indeed hovering over them does not change the cursor to indicate it's a link at all.
Presumably to do with some of the other many changes today!
![screenshot - 2016-06-23 14_39_41](https://cloud.githubusercontent.com/assets/8819910/16303323/57437722-3950-11e6-964a-251023eb03c0.png)

**Comment by runjak** [comment]
Which browser are you using?
I cannot reproduce this on either Chromium or Firefox on the currently deployed version.

**Comment by runjak** [comment]
Well - that is I can reproduce it with a browser window that still has content cached.
I think this is a cache issue.

**Comment by runjak** [comment]
I'll aim to fix the caching problematic as it becomes especially annoying when updates are more frequent.

**Comment by PaulHeggarty** [comment]
You’re right, I’ve cleared my browser cache and the problem has gone away. I’m very surprised, I didn’t think the cache could interfere wIth things like this.
You’re also right that this cache thing is really becoming more annoying now, so it's worth investing some time to try to fix it.

**Comment by runjak** [comment]
I'll change the description of this issue to make it about fixing the caching situation.

**Comment by runjak** [comment]
I found that a [plugin](https://github.com/requirejs/text) for our javascript [module loader](http://requirejs.org/) exists that allows me to include templates in the javascript code directly. This should make it possible to reduce load times and solve part of the caching problematic at the same time.

**Comment by runjak** [comment]
I've implemented a cache fix for the minified JavaScript.
This fix is similar to the one done in CoBL in principal but differs in the implementation.
While the CoBL setup allows us to precompute a [hash](https://en.wikipedia.org/wiki/Cryptographic_hash_function) of the minified JavaScript in advance due to a better minification process, this hash is calculated each request in soundcomparisons.

This issue will be closed once the fix is deployed.
