### ISSUE TITLE
Pasting revised transcriptions - old and new

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#393]
The revised transcription to Letemboi: Newotenyene isn't showing up on my browser. I don't know if it got uploaded or not. It also looks like there's at least one old revised transcription that didn't get uploaded: Nasarian. Another issue with the Newotenyene, as I indicate on the spreadsheet in the column next to the transcription, is that two words are from a different speaker ('belly' and 'big'). It's funny in the Praat marked-up file because those two words appear at the end (not in their usual order). I know it's a pain to fish out individual words, but it really is just too obvious when the speaker sounds 40 years younger, so when you get a chance, please do pull those out, along with 'road', 'stick/wood', and 'fish', which are not 'road', 'stick/wood' and 'fish'. I'm attaching the Newotenyene transcription as well as the Nasarian. Please, if you suspect that there are any others that might not have gotten uploaded, do upload them before tomorrow afternoon. I'm going to have to go through and figure out what's been uploaded and what hasn't, and it will be easier for me if there aren't too many discrepancies to sort through. I'll upload a sheet to oc that puts all 90-however-many of them together. Thanks!

**Comment by AvivaShimelman** [comment]
Transcriptions attached
[Letemboi Nevatanyene and Nasarian corrections 2016 06 24.xlsx](https://github.com/lingdb/Sound-Comparisons/files/332497/Letemboi.Nevatanyene.and.Nasarian.corrections.2016.06.24.xlsx)

**Comment by AvivaShimelman** [comment]
I've uploaded to oc and attached here a spreadsheet compiling the current versions of all transcriptions listed on the current reference sheet (2016 06 16 (2)). 13 are marked "not revised." Of these, 11 are "short list" recordings (i.e., recordings for which we have full transcriptions but only 57 words marked up (i.e., with sound) on SC). 7 are marked "turned off." All others have "pre-edited" recordings and revised transcriptions. I will be getting to the "short list" recordings over the next two weeks.
[2016 06 24 Malakula transcriptions compiled.xlsx](https://github.com/lingdb/Sound-Comparisons/files/332766/2016.06.24.Malakula.transcriptions.compiled.xlsx)


For LAURA, there are 7 in "to clean up" that are really important to have done before Heidi leaves. 10 are waiting in "don't worry about; 13 will be joining those in the next two weeks. Those 20 can be taken with calm, but, of course, they're not going to disappear, and would be surely glad to gain full citizenship on sc sooner rather than later.

**Comment by LauraWae** [comment]
I will close this issue now. Its contents aretreated in #367 and #350 .
