### ISSUE TITLE
Mapudungun page shows map incorrectly on refresh

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#414]
When refreshing (F5) the [Mapudungun page](http://soundcomparisons.com/#/en/Mapudungun/map/seven/Lgs_Sln), the map is displayed incorrectly -- about 3.5 global maps are shown horizontally (see screenshot).

Note that this does _not_ happen when initially loading the page (by pasting the URL in the URL bar, for example). Note also that the problem is fixed by clicking on the "Reference Forms" option.

![screenshot_20170118_171043](https://cloud.githubusercontent.com/assets/5791472/22071972/1e16984e-dda1-11e6-91dc-3ba1a07f3cd0.png)

**Comment by runjak** [comment]
I have problems reproducing this in either Firefox or Chromium/Chrome.
Can you tell me whether this problem also persists in the private mode of your Browser,
and which Browser you're using?

**Comment by Linguista** [comment]
Pleasantly enough, I can't reproduce this problem now either, so I can only assume it was an issue with data cached in my browser (I was using Chromium 55 on Linux). I think you can close this issue.
