### ISSUE TITLE
Insert  \n between altlex transcriptions

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#415]
Currently, when a given word has two alternate lexemes (and presumably if it has more), their phonetic transcriptions are displayed side-by-side, as in this image:

![image](https://cloud.githubusercontent.com/assets/5791472/22256311/a4c8a004-e25a-11e6-9745-f70c5e79b54e.png)

Sometimes both transcriptions fit in the cell assigned to the word, but many times they don't, as the screencap illustrates. 

In order to fix this, I would suggest inserting a `\n` (newline) between each phonetic transcription. This would, of course, make the occasional table row taller than the rest, but I think that's a better solution than having transcriptions overlap into neighboring cells.

**Comment by Bibiko** [comment]
fixed with issue e6133bc87d31609cc22bb782c0f06f428b411337
