### ISSUE TITLE
Maps' phonetic transcription boxes' right margins too tight

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#416]
This is undoubtedly a _very_ minor issue, but the right margin of the boxes in which phonetic transcriptions appear on the maps is too tight. In fact, it appears that there actually is no margin (the left margin, on the other hand, seems to be about 2 px wide).

This has the effect of making the last character of each transcription somewhat difficult to read. This image shows an example:

![image](https://cloud.githubusercontent.com/assets/5791472/22296831/ae64d62a-e31b-11e6-8486-50ac0164e78b.png)

**Comment by Linguista** [comment]
Another screenshot to show what's going on. Here, the serif on the right part of the phonetic symbol is displaying _outside_ the box. So it's more than just having a 0 px right margin, apparently.

![image](https://cloud.githubusercontent.com/assets/5791472/22313056/10af0e42-e35b-11e6-9df0-bcd39064db14.png)

**Comment by Bibiko** [comment]
fixed with commit e6133bc87d31609cc22bb782c0f06f428b411337
