### ISSUE TITLE
Anomalous transcription display

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#417]
I have just come across an anomaly in the display of at least one transcription. 

Language: Mapudungun
Lexical item: "fülang, lig, lüg", 
Speaker: Puerto Saavedra
Display: Map

The speaker produced two lexemes for this word. Instead of being shown side-by-side, as is still normally the case, one is shown above the other, but with a comma taking up a second row. As a result, the two words are shown on three lines, and the third line is essentially invisible, and is outside the box.

![image](https://cloud.githubusercontent.com/assets/5791472/22297326/3cf2acb8-e31d-11e6-9ae2-34dd9ab2fb8f.png)

It's actually more visible in this screenshot:

![image](https://cloud.githubusercontent.com/assets/5791472/22297534/e6dcfe7c-e31d-11e6-8238-8b80fc41ee0e.png)

**Comment by Bibiko** [comment]
for now I fixed this issue – further improvements will come in the near future
