### ISSUE TITLE
Admin page's "Upload" and "Diagnostics" menus do not pop up anymore

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#418]
Not sure when this problem started, but the "Upload" and "Diagnostics" buttons on the administration page no longer show their respective popup menus, which means I can't get to the SQL upload page and other admin pages. This is happening on the following browsers, all in Linux:

- Chromium 55.0.2883.87 Built on Ubuntu , running on neon 16.04 (64-bit)
- Firefox 51.0.1 (64 bit)
- Chrome 56.0.2924.76 (64-bit)
- Opera 42.0.2393.517 
- Qupzilla 1.8.9 / WebKit version 538.1

**Comment by runjak** [comment]
I have an idea what caused this.
Will see to fix it today.

**Comment by runjak** [comment]
This is working again now on the server.
