### ISSUE TITLE
Separate tab for adding new studies in admin system 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#423]
In the admin system, two functions are combined onto a single page at:

http://www.soundcomparisons.com/admin/dbimport.php

See the two halves of this screenshot:  

![screenshot - 2017-02-02 17_08_48](https://cloud.githubusercontent.com/assets/8819910/22557470/e97e1bb8-e96a-11e6-97ee-b68456968838.png)

The two halves are very different tasks, and should be set to different screens.  Adding a new Language Family (please rewrite with a space between the words, by the way) should not be on this screen, but on a separate screen, reached not from the `Upload` tab in the header, but from a separate tab called `Add New Study`.  

This new tab should only be usable by users with full admin rights.  (Indeed we need to move to a new system of user rights, but that's for a later issue.)

**Comment by Bibiko** [comment]
I refactored the admin/upload interface and I renamed the tab into 'Database' since there're several commands which all have something to do with the underlying database. In respect of more fine-grained access rights I'll open a new issue.
