### ISSUE TITLE
Bugs with Translation System

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#424]
On 2017-01-17 @Linguista mentioned some problems:

----
- [x] When the interface is set to Spanish, the "DS" subscript tooltip comes up in English, even though I know I translated it. (here, for example)

- [ ] When the interface language is Spanish, the "Further Info", "Research" and "Contact" options (selected from the info button) bring up English pages. If these are static pages, I'd be glad to translate them if you let me know where that can be done.
- [x] The "Main Contributors", etc., page doesn't seem to use the Spanish translation performed through the site. This is apparent because I changed all instances of "contribuyentes" ('taxpayers') to "contribuidores", but that change hasn't propagated to this page.

**Comment by Bibiko** [comment]
@PaulHeggarty 
at 1) could you please provide an example 
at 2) translated sites are static sites within this wiki; simply add a new Spanish wiki page e.g. About-Page:-Mas-Info, write some context, and add via admin>translate>Spanish>General [look for "About-Page"] and save the correct new URL [in that case: #/about/About-Page:-Mas-Info]
at 3) this is a bug I'm just digging in

**Comment by PaulHeggarty** [comment]
Actually, these issues were raised by @Linguista, so best if he could respond to your points on 1 and 2.  Thanks for the clarification on 2.  The main point here is that the English pages are still not written!  When I get a chance to, then I’ll request translations in some of the major site languages (but not all -- too much work!).

**Comment by Bibiko** [comment]
at 3) fixed

**Comment by PaulHeggarty** [comment]
Hmm, fixed and debugged at 1:03 am on a Monday morning.  You really will fit in with the Sound Comparisons team!  ;)
Many thanks!

**Comment by Bibiko** [comment]
at 1) fixed

**Comment by Bibiko** [comment]
since 2) isn't an issue on the code side, I assume that we can close this issue

**Comment by Linguista** [comment]
> since 2) isn't an issue on the code side, I assume that we can close this issue

We should probably make a new issue for 2), since it needs to get done at some point, but I'll leave that decision to @PaulHeggarty. This is the issue:

> When the interface language is Spanish, the "Further Info", "Research" and "Contact" options (selected from the info button) bring up English pages. If these are static pages, I'd be glad to translate them if you let me know where that can be done.
