### ISSUE TITLE
New Malakula recordings - file names, corrected recordings, Giovanni's transcriptions

### ISSUE THREAD

**Issue by AvivaShimelman** [lingdb/Sound-Comparisons#432]
"A few minutes" - just a couple of questions for now.

I have the new Access sheet done and I'm working on the recordings. I wanted to check how we want to handle the odd-ball ones, though. 

In most cases (21), we simply have straight-out new recordings, and, I assume, those will get listed/treated as all previous ones have. In 8 cases, though, I returned to the same speaker and had them correct (re-record) the "offending" terms. Usually, there are about 15-20 terms that were ultimately re-recorded. There are three issues that have to be dealt with in these cases, as far as I can see:

@LauraWae 
Is it better for you if I cut and paste the changed terms into the old recording or if I just pre-edit the new recording with just the 15-20 terms? You'll have the transcriptions, of course, either way, and the terms, in the case of the abbreviated recordings are in the same order as they would be in the full recordings. My overwhelming preference would be to take the second route. In the first case, you would just treat it as a new recording, I would think, and then remove the corresponding old recording from the site. In the second, you would just replace selected entries.

How do you want these recordings labeled? For the moment, I am giving them the old file numbers and names with an "R" appended to the number and a "tail" on the file name, "revisions."
Example:
wl_0010_Avava_Tisvel --> wl_0010-R_Avava_Tisvel_revisions

A very big issue (I didn't think about this early enough). Five of the revised recordings are among those that Giovanni transcribed. Thirty of the terms Giovanni transcribed are potentially inflected in some way. So there is some overlap -- different in every case -- between the terms he transcribed and the ones the speakers corrected. There are, total, I think, some 60 terms that Giovanni transcribed that will now no longer match the recordings that will be heard on the site. So, if and when Giovanni's recordings make it to the site, his transcriptions for these terms will have to be struck, I would think (unless there can be some kind of "legacy" version of the site). 

The affected recordings are:
Najit
Wala_Worprev
Venen Taute_Alpalak
Tirax_Mae
Navwien_Mbonvor (unavoidable -- single speaker)

The potentially affected terms (no recording had to be corrected for every one of these) are:

hand
to come
back
belly
blood
head
nose
mouth
tooth
tongue
to vomit
to spit
to eat
to drink
ear
to hear
eye
to see
to sleep
to hunt
to shoot
to steal
dead
live
sharp
pay
open
black
small
new

As I upload the transcriptions, I'll mark these. I don't know what else can be done.

Aviva

**Comment by LauraWae** [comment]
Hi Aviva,
Thanks for your detailed description. Kerstin has already reported that the SD-card has arrived in Jena. So, on Tuesday I will have a look at it.

> Is it better for you if I cut and paste the changed terms into the old recording or if I just pre-edit the new recording with just the 15-20 terms? You'll have the transcriptions, of course, either way, and the terms, in the case of the abbreviated recordings are in the same order as they would be in the full recordings. My overwhelming preference would be to take the second route. In the first case, you would just treat it as a new recording, I would think, and then remove the corresponding old recording from the site. In the second, you would just replace selected entries.

Please, pre-edit the new recording with just the 15-20 terms. There is no problem in overwriting the existing, now "old" ones on the server.

> 
> How do you want these recordings labeled? For the moment, I am giving them the old file numbers and names with an "R" appended to the number and a "tail" on the file name, "revisions."
> Example:
> wl_0010_Avava_Tisvel --> wl_0010-R_Avava_Tisvel_revisions
Thats fine for me, thanks for considering.

All the best,
Laura

**Comment by AvivaShimelman** [comment]
Hi, Laura,

Nononononono ... The SD card is addressed to me. I sent it to myself . It was just a way of squirreling data away in another place until I got somewhere where I would be able to upload the files. Just hold on to the card, please. Those files are not "website ready."

A.

**Comment by LauraWae** [comment]
Hi Aviva,
Ok, thanks for advising,
L.

**Comment by LauraWae** [comment]
Hi @AvivaShimelman 
In your list of potentially affected terms above, you mention the word "pay". We have not used this word before, so, after doing some semantic reflection exercises ;), I suppose it refers to "buy". However, those are two different meanings. Do we need to change that word in our list of glosses? Thanks.

**Comment by LauraWae** [comment]
Hi again @AvivaShimelman 
I have a question about the revised files.
Do I only have to extract the words which are on your list above (hand,..., new)? Or do you want to extract me each word that those files contain? Thanks for replying.

**Comment by AvivaShimelman** [comment]
No need for changes. In Bislama, "pem" is 'buy.'

A.

On 2/21/17, LauraWae <notifications@github.com> wrote:
> Hi @AvivaShimelman
> In your list of potentially affected terms above, you mention the word
> "pay". We have not used this word before, so, after doing some semantic
> reflection exercises ;), I suppose it refers to "buy". However, those are
> two different meanings. Do we need to change that word in our list of
> glosses? Thanks.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lingdb/Sound-Comparisons/issues/432#issuecomment-281319651


-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment]
I'm not sure what list you're referring to. The general answer ****
with regard to the R files **** is that if a word is in the recording,
it is meant to be extracted (i.e., meant to go on the site, replacing
any word that is already there, if there is one). This applies both to
the words that replace those Giovanni transcribed as well as those
which I alone transcribed. All other words from the original file
should remain undisturbed. Please let me know if that makes sense.

A.

On 2/21/17, LauraWae <notifications@github.com> wrote:
> Hi again @AvivaShimelman
> I have a question about the revised files.
> Do I only have to extract the words which are on your list above (hand,...,
> new)? Or do you want to extract me each word that those files contain?
> Thanks for replying.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lingdb/Sound-Comparisons/issues/432#issuecomment-281340246


-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment]
Hi, got that. Thanks. Good reason to switch off the two languages for which I did R-files yesterday. Will return to this when I have re-done them.

**Comment by AvivaShimelman** [comment]
I think so. They'll all be getting up over the next couple of weeks in
any case.

A.

On 2/22/17, LauraWae <notifications@github.com> wrote:
> Hi, got that. Thanks. Good reason to switch off the two languages for which
> I did R-files yesterday. Will return to this when I have re-done them.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lingdb/Sound-Comparisons/issues/432#issuecomment-281604422


-- 
Aviva Shimelman, PhD
