### ISSUE TITLE
Make more powerful version of auto-create-tiers-and-speech-segments.praat

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#435]
_Our previous exchange on this matter has become convoluted enough that I'm going to make a new issue (this one) with a design spec based on what I understand to be the consensus on each issue. Please comment on any errors, problems, omissions, etc._

The next version of the `auto-create-tiers-and-speech-segments.praat` (version 3) should do the following:

1. Autodetect the language of the recording being processed, using the first part of the recording's file name.

1. In the autodetect function, recognize the following naming conventions (can be expanded later if necessary):
a. `Br_` (Brazilian languages - All)
b. `Oce_Van_` (Oceanic languages - Vanuatu (Malakula)). 
_NOTE 1: As the index file `Malakula_index.txt` is specific to Malakula, the language autodetection should be specific to this group, too (and not general for anything Oceanic)._
_NOTE 2: For consistency's sake, it would be desirable to harmonize the naming conventions for sound and index files. For example, call the index file `Oce_Vanuatu_index.txt` and maintain the convention of starting the sound files with `Oce_Van_`. Or, alternately, call the index file `Oce_Malakula_index.txt` and change the sound file naming convention to `Oce_Mal_`. The current system is simply confusing!_

1. Add a `Detect and segment speech` option.

1. If the `Detect and segment speech` option is selected, do the following:
a. Create the standard Sound Comparisons text grid with one additional (temporary) tier, `**AUTO DET**`, for placing the `s` that marks auto-detected speech segments.
b. This option will also eliminate any previous work done on a text grid, making it easy to start over.
c. Detect silent segments and segments with what the detection algorithm believes is speech.
d. Add user-specified left and right margins to the times the detection algorithm comes up with.
e. Create segments for both of these things in all tiers (except for the `**DEBUG**` tier, which is processed differently (if it exists)).
f. Mark the segments believed to contain speech with `s` in the `**AUTO DET**` tier.

1. Modify the `Debug` option so that:
a. It is called `Debug segmentation`.
b. It creates a tier called `**DEBUG**` where user-added margins are _not_  added.
c. The speech code `s` is _not_ written in this tier.

1. Create an `Insert glosses` option.

1. If the `Insert glosses` option is selected, do the following
a. Read in an index file for the appropriate language. Initially, these files will be  `Brazil_index.txt` and `Malakula_index.txt`. More may be added later.
     As **these files must be read locally**, the user will be responsible for downloading the right one from the appropriate ownCloud directory. The script can easily throw an error if the right language file is not present, but **it has no way of knowing if the file was downloaded from the appropriate folder**.
     Therefore, I strongly suggest that all index files be placed in one centralized folder (e.g. `/Index files`), and all non-current ones be placed in another which is named in such a way as to discourage their use (e.g. `/Deprecated/Index files`). 
b. Iterate through the text grid and when `s` is found in the `**AUTO DET**` tier, insert the corresponding content of the first column (`gloss`) of the appropriate `*_index.txt` file into the `Rfc_form` tier.

1. Create a `Double word elicitation` option for recordings in which each lexical item was elicited twice in a row.

1.  If the `Double word elicitation` option is selected, insert each `gloss` item two consecutive times in the `Rfc_form` tier of the text grid. Thus, when this option is checked, instead of inserting `house` | `cat` | `dog`, the script will insert `house` | `house` | `cat` | `cat` | `dog` | `dog`.

1. Create a `Double list elicitation` option for recordings in which the entire elicitation list was read through two times.

1.  If the `Double list elicitation` option is selected, insert the `gloss` items from the index file into the `Rfc_form` tier of the text grid two times, one after the other. Thus, when this option is checked, instead of inserting `house` | `cat` | `dog`, the script will insert `house` | `cat` | `dog` | `house` | `cat` | `dog`.

1. If the script mistakenly treats linguistic silence (such as background noise) as speech, the glosses inserted from that point forward (rightward) will end up shifted to the left of where they should be. In this case, users have two options:
a. If there are many such errors, re-run the script with different parameters.
b. If these errors are few and far between, manually delete the `s` from segments mistakenly identified as speech and then re-run the script while checking **only** the `Insert glosses` option.

1. If the script mistakenly treats speech as silence, the glosses from that point forward (rightward) will end up shifted to the right of where they should be. In this case, the user has two options:
a. If there are many such errors, re-run the script with different parameters.
b. Manually label the offending segment with `x` and re-run the script with **only** the `Insert glosses` option selected. The script will skip over segments with `x` when inserting glosses.

1. Create a `Finalize` option which will do the following:
a. Delete the `**DEBUG**` tier, if it exists.
b. Delete the `**AUTO DET**` tier if it exists.
c. Save the text grid.

**Comment by PaulHeggarty** [comment]
On point 2, the reason it's called Malakula_index is because the name of the study across the website is Malakula.  It's future proofing that sound-files have Oce_ in them.  If and when we get to that stage, we can change the study name to Oceanic, but to pretend that would be a gross exaggeration at the moment.  We may within a year change its name to Vanuatu, if we get enough recordings from outside Malakula.  

But for now, I think it should stay as it is, except perhaps for changing the index file name to Oceanic_index.  But that would need a tweak from Hans-Jörg too, to other scripts, I presume.

**Comment by Linguista** [comment]
I've finished this script, and the new version (3.0) can be found in the Praat scripts directory on our **[ownCloud](https://oc.gnz.mpg.de/owncloud/index.php/apps/files/?dir=%2FSndComp%2FAll%20-%20Scripts%20for%20Praat)**. It's called `auto-create-tiers-and-speech-segments.praat`.

It seems to work correctly, but of course it could do with testing, so test away!

I'm beginning to write some documentation [here](https://github.com/lingdb/Sound-Comparisons/wiki/Manual:-auto-create-tiers-and-speech-segments.praat).
