### ISSUE TITLE
User/group problems on newly-uploaded sound files

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#437]
The audio files that I upload to the server (using SSH over the MPI VPN) still inherit my user and group (`sadowsky:sadowsky`), which means the Sound Comparisons website can't read them. Their user and group need to be changed to `soundcomparisons:soundcomparisons`, but I don't have sufficient permissions to do that.

Something similar was reported in #421. At the time, @runjak mentioned the following possible solutions:

> If I'm not mistaken using ACLs it should be possible to force files created in a directory tree to inherit a certain group, but I'm not sure if this will work in all cases.
> The easier but technically not as satisfying solution would be some kind of cron job or systemd timer that adjusts the file permissions every once in a while (hour or day should suffice).

However, it seems that a solution has yet to be implemented. Until something is done, the recordings for 9 Mapudungun varieties won't work on the website, nor will future uploads (at least by me).

**Comment by Bibiko** [comment]
I'll install a service which runs all 4 hours to fix user and group but also permissions (664). @Linguista can you check after clearing the cache if your newly uploaded sounds are working?

But, my over-all aim is to come up with an admin interface which allows to simply select a local folder and to upload all sound files to the server, including to set all permissions etc. correctly. 
On my local machine it works but it needs a lot of additional safety mechanisms which I've to implant first.

**Comment by Linguista** [comment]
Just checked, and everything appears to be working perfectly. Thanks for the quick response!

A full-featured admin interface would be great, by the way.
