### ISSUE TITLE
Pictures for WIKI

### ISSUE THREAD

**Issue by LauraWae** [lingdb/Sound-Comparisons#445]

**Comment by LauraWae** [comment]
![capture](https://cloud.githubusercontent.com/assets/10007762/23122115/32ed4cc8-f763-11e6-82cb-2774eb59a2f4.JPG)

**Comment by LauraWae** [comment]
![capture2](https://cloud.githubusercontent.com/assets/10007762/23122338/1795742c-f764-11e6-8fe8-d4ee6a278ea7.JPG)

**Comment by LauraWae** [comment]
![capture2](https://cloud.githubusercontent.com/assets/10007762/23122429/75decc0e-f764-11e6-8816-bfa039a6bce3.JPG)

**Comment by LauraWae** [comment]
![capture3](https://cloud.githubusercontent.com/assets/10007762/23122496/b9ab66e0-f764-11e6-88d7-bf50b7f26424.JPG)

**Comment by AvivaShimelman** [comment]
Morning!

Question about flow chart --
Can you mark up an unfamiliar language without the transcription? You
have transcription listed as the last task. (?)

A.

On 2/20/17, LauraWae <notifications@github.com> wrote:
> ![capture3](https://cloud.githubusercontent.com/assets/10007762/23122496/b9ab66e0-f764-11e6-88d7-bf50b7f26424.JPG)
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lingdb/Sound-Comparisons/issues/445#issuecomment-281051006


-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment]
Morning!

I know this is a draft, so you'll get to these things later, but you
will forgive an old English professor for having a thing for "parallel
structures."
Preferable to -
use the same structure throughout, i.e., either full sentences or
subject-less bullets (my preference) throughout and then either
initial caps or no caps (my preference) throughout.

A.

On 2/20/17, LauraWae <notifications@github.com> wrote:
> ![capture2](https://cloud.githubusercontent.com/assets/10007762/23122338/1795742c-f764-11e6-8fe8-d4ee6a278ea7.JPG)
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lingdb/Sound-Comparisons/issues/445#issuecomment-281049708


-- 
Aviva Shimelman, PhD
