### ISSUE TITLE
Create Automated 'ReName Language' Function in Admin Section

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#447]
Unfortunately we fairly often need to rename a language 'FileName'/URL string, e.g.. Oce_Van_Mal_Nth_WSth_VenenTaute_Hamax_Dl
This often has to be done for reasons of consistency, and especially when another close variety gets added.  

At the moment, it is easy for me to do this in my Access database, and upload the new names to the data tables.  But it is **not** easy to change all the sound file names on the server.  What we need is a new admin function "ReName SoundFiles for a Language", to do this automatically.  This should:
1) Ask the user to input the old name (to be changed) - without any extension like .mp3. 
2) Check that that old name is actually in use, i.e. there is a folder with that name in the /sounds folder on the server (and some files in it?).
3) Ask the user to input the new name (that it is to be changed to).
4) Check that the new name makes sense according to filenaming standards.
5) Change the name of the corresponding folder on the server.
6) All individual files within that folder should start with the same name string, plus the various identifiers for each individual word, plus the extensions, usually copies of each sound file in three sound formats, .wav + .mp3 + .ogg.  All of these need to be renamed.

**Comment by Bibiko** [comment]
@LauraWae @PaulHeggarty For this purpose I've already written a script. Since this script is doing stuff direct on the server, its's safer that I run this script on demand manually in order to avoid having problems with permissions and in addition to control the script if it fails for some reasons. Thus write me a mail with `OLD_NAME` `NEW_NAME`.
