### ISSUE TITLE
Multiple contributors not displaying properly

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#449]
In an example language like http://www.soundcomparisons.com/#/es/Mapudungun/language/Curarrehue there are two people who did the recording, identified in the languages table input as 
`Contributor:  Recorded By 1` and `Contributor:  Recorded By 2`.  This should give two corresponding rows on that webpage, under the drop down people icon.  Instead, it only gives one row, with contributor 2 overwriting contributor 1.

**Comment by Bibiko** [comment]
There were a few general bugs in this issue. Should now work. [The former assumption was that **one** contributor was responsible for only **one** task] In addition I also fixed an issue for ContributorCitationAuthor1/2.
