### ISSUE TITLE
Offline Version:  Phase 2

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#452]
Jakob created a system to create exports of all the data needed to run Sound Comparisons offline.  We could do with a new export, especially because the old one didn’t have the Brazil project included.  I’m at a meeting in Sweden with the main organiser of the Brazil project, so it would be nice to put an offline version on her laptop, if possible.

**Comment by Bibiko** [comment]
@PaulHeggarty Which sound files of which studies should be involved? And, how to share the 3 4 GB data? One could think of a mechanism at www.soundcomparisons.com where one is able to select which studies one is interested in and press a download button to get the Offline version since @runjak had really cool ideas to create this Offline version.

**Comment by LauraWae** [comment]
Hi,

We used to share the offline versions via Dropbox. 

I like the idea of pressing a download button to get the offline version. In the Brazilian export, all files that start with "Br_,..." should be included. 

There is, thus, a coworker in Brasil, Denise Silva, who is currently travelling, but promised to send me one file at the beginning of April. It's the Terena file which is still missing on the map.

I think it is worth to wait for Denise to send the file, so Terena can be included, too, in the offline version.

**Comment by Bibiko** [comment]
ok - this means, this version contains **only** sound files for the Brazilian branch. The point here is that the main part in respect of size cover the sound files. Dropbox - ok - whose account?

**Comment by PaulHeggarty** [comment]
To respond at last to @Bibiko above, yes, it would be ideal to have a way to download things separately, as needed for any particular user:
* Obviously, all downloads should include the base programme in its latest form.
* The map files should be separate, and not included in a download by default, because for any user who already has them, they will not normally need to be updated.
* The recording audio files should be downloadable for each study separately, so that people who need Malakula, for example, only need to download those sound files.  Let users choose which studies they want.

- [ ] One last request:  currently the map files are only available in the basic view, which isn’t very pretty.  Online we also have `Esri Nat Geo World Map`, and `Esri World Imagery`.  Is there any way to get those too?  I know it's lots of file size and time, but I’d much rather use these for offline demos too, and once it's copied once (by USB stick?) then it won’t need to be updated.

- [ ] Is there also a way to save beyond level 17 for small areas where we need better offline resolution, in particular Malakula island, and the Mapudungun region of southern Chile and Argentina?

**Comment by PaulHeggarty** [comment]
Laura refers to a recording of 'Terena' in Brazil, but I know nothing more of this, so please just proceed with the update without that variety for Brazil.  I’ll check up, but we should not wait for it.

**Comment by PaulHeggarty** [comment]
I presume we still need to contact @runjak to ask for his code for doing the exports again.  Can you confirm, @Bibiko?

**Comment by Bibiko** [comment]
I can generate the needed data files. But to generate new map tiles I need the help of @runjak.

**Comment by runjak** [comment]
Hey!
I'll have a look at it once I'm home - this shouldn't be too complicated to do, I hope.
Basically what I did then was something along these steps:
1. Run a docker container with an OSM server in it
2. Have a script load the wanted map tiles from that server
3. Discard the OSM server but keep the map tiles

**Comment by Bibiko** [comment]
@runjak Your point 1) is the problem so far. I created such a docker but I couldn't replace the mbtiles file. Now I'm trying to run this server via node on my local Ubuntu VM and it seems to work. I keep you informed when I need further help :)

**Comment by Bibiko** [comment]
Finally I was able to set up such a map server on my local machine. In addition now we can change the default landmass background like:
![10 2x](https://user-images.githubusercontent.com/16273/33105127-011aaee2-cf2c-11e7-9159-61d72124c5fb.png)

**Comment by PaulHeggarty** [comment]
Excellent, it looks great!

**Comment by runjak** [comment]
Glad to hear you've got this working & sorry it has been such a hassle.

Also very cool to hear you can configure the background settings!

**Comment by Bibiko** [comment]
@PaulHeggarty @cormacanderson : A short interim report. My computerS are calculating the new background map for the offline version (@runjak : I do this on three different computers running six docker map tile server == distributed server loads :) Here two impressions after one hour of calculations :
![a2](https://user-images.githubusercontent.com/16273/33136613-f202c7bc-cfa5-11e7-802d-cac0e4e30722.jpg)
![a1](https://user-images.githubusercontent.com/16273/33136619-f58a89ba-cfa5-11e7-825d-20c7160190e3.jpg)

**Comment by PaulHeggarty** [comment]
Thanks for getting back to us on this, @runjak.

**Comment by PaulHeggarty** [comment]
Looking great.  I expect Russell will also be happy to have this for the new offline version for Malakula.

**Comment by PaulHeggarty** [comment]
Closing this because this phase is complete now.  Opening a new issue #470 for outstanding points.

**Comment by PaulHeggarty** [comment]
It's not me sending you emails, it's github, I presume.  You need to remove yourself from the soundcomparisons users group, I presume.

**Comment by runjak** [comment]
Usually you can also remain part of the users group, but adjust the notification settings in your GitHub user account. You should have a settings page looking roughly like this:

![screenshot_2018-02-04_12-37-59](https://user-images.githubusercontent.com/5417642/35777103-585f4bfc-09a8-11e8-8fd1-165d2e08794c.png)

Teams and projects on GitHub can be marked as watched by your user - this selects which parts of the platform your notification settings apply to. You won't get stuff about things you don't watch. There is a `watch` button at the top of the project page and a list of watchers associated with it:

https://github.com/lingdb/Sound-Comparisons/watchers
