### ISSUE TITLE
Switch lat-long back on on map

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#454]
On the SoundComparisons map, Jakob originally showed (down in the bottom left corner) the latitude and longitude of whatever point the mouse/cursor was at on the map, changig as the user moved the mouse.  Please switch this back on, if you can find the code again!

**Comment by Bibiko** [comment]
@PaulHeggarty I put the coordinates above the map right to keep the map clean. Ok? Is the format ok?

**Comment by PaulHeggarty** [comment]
Very good choice, yes it's great like that.  One last request, though.  Rather than degrees, minues, seconds, could we have decimal degrees, please, since that's the system we use in the database.  Also, it can be limited to six or seven decimal places, I think, because that already gets us down to 7m or so.  (I think we need one more place for latitude than for longitude, or something.)

**Comment by Bibiko** [comment]
six places should really be enough - also, I'll add a setting for it how to display (which format) in the near future
