### ISSUE TITLE
Progress Tracker:  Malakula Data:  Culture Lists 2

### ISSUE THREAD

**Issue by LauraWae** [lingdb/Sound-Comparisons#460]
This is to track the progress being made on tagging the Culture List recordings.

**Comment by LauraWae** [comment]
**wlc_1630065_Malua_Bay_Petarmul_selected**
 - tagged.

**Comment by AvivaShimelman** [comment]
@LauraWae 
Hi! A good idea to start a new new tracker. Does this mean you started with this one (Petarmul)? Or did you do Najit before creating the issue? Any issues? Do you want me to double-check it at any point? Do you have a sense of how long each one will take once you get a rhythm going?  A.

**Comment by LauraWae** [comment]
**wlc_1630068_Najit_Tanmial_selected**
- tagged. 
- Sound and texgrid saved to `ownCloud\SndComp\Malakula\Culture List\02 Tagged Files and Textgrids`.

**Comment by LauraWae** [comment]
**wlc_1630066_Espiegel_s_Bay_selected**

- tagged.
- Sound and texgrid saved to `ownCloud\SndComp\Malakula\Culture List\02 Tagged Files and Textgrids`.

**Comment by LauraWae** [comment]
**wlc_1630064_Siviti_Gonwar_selected**

- tagged.
- Sound and texgrid saved to `ownCloud\SndComp\Malakula\Culture List\02 Tagged Files and Textgrids`.

**Comment by LauraWae** [comment]
**wlc_1630064_Siviti_Gonwar_selected**

- tagged.
- Sound and texgrid saved to ownCloud\SndComp\Malakula\Culture List\02 Tagged Files and Textgrids.

**Comment by LauraWae** [comment]
**wlc_1620034-R_Tirax_Mae_revised_selected**
- tagged.
