### ISSUE TITLE
Where do I find the actual data on phonetic transcriptions?

### ISSUE THREAD

**Issue by LinguList** [lingdb/Sound-Comparisons#461]
In order to help by giving recommendations on best practice of phonetic transcriptions (I see they are currently just taken unchecked from the transcribers, but do you at least normalize to one unicode version?), I need to be pointed to the raw data. Is this uploaded in some project? Do you plan on uploading it? And how do you get it into the SoundComparisons? This remains a mystery for me, but it is crucial if you want to increase the synergies with our work on standardization.

**Comment by LauraWae** [comment]
Hi Mattis,

In general, we use SQLs to upload transcriptions to the website. I will send you such an example per E-Mail, as Github does not allow Excel-Sheets. Paul creates those sheets. Transcribers enter their data to it.

I do not know if you have access to the Owncloud Folder System of Soundcomparisons. Most (!) of the raw transcriptions can be found there. Please tell me if you need further indications.

**Comment by LinguList** [comment]
Thanks, this is indeed really helpful. I'd suggest to share these things online, or even better, to have them converted to regular csv-files (with the info inside) and then track them on github. This is also good for versionizing. If those excel things are converted to the database representation anyway, it is a no-brainer for a programmer in doing the same conversion to the [cldf](http://github.com/glottobank/cldf) formats, we are currently developing.
