### ISSUE TITLE
Contributors pages are now blank

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#463]
The `Contributors` pages are now coming up blank for some reason. I've confirmed this in language varieties from the Quechua, Romance and Slavic families, using three different browsers.

**Comment by Bibiko** [comment]
The problem was that the entire Contributors SQL table was empty. I fixed it by importing my local data but these data doesn't reflect the last changes.

@PaulHeggarty Did you change or update the Contributor table?

**Comment by PaulHeggarty** [comment]
I only added some cotributors and uploaded it, about 10 days ago.  I didn’t get an error message.  I’ll now re-upload.  Here's the file.
[Contributors.txt](https://github.com/lingdb/Sound-Comparisons/files/952654/Contributors.txt)

**Comment by PaulHeggarty** [comment]
OK: that does give an error:  

Importer::processFiles for uId 2; merge=
Importer::mkQueries for Contributors.txt…
Columns to import: ContributorIx, SortGroup, SortIxForAboutPage, Forenames, Surnames, Initials, EmailUpToAt, EmailAfterAt, PersonalWebsite, FullRoleDescription
Importer::execQueries for User 2
Error with query 'INSERT INTO Contributors (ContributorIx,SortGroup,SortIxForAboutPage,Forenames,Surnames,Initials,EmailUpToAt,EmailAfterAt,PersonalWebsite,FullRoleDescription) VALUES (1,1,1,'Paul','Heggarty','PAH','Paul.Heggarty','gmail.com','http://www.tinyurl.com/paulheggarty','Founded and administers this website and the associated linguistic research project. \r\nDevised the website and database structure. \r\nProgrammed the first versions of these websites. \r\nRecorded most languages of most families except the accents of English. \r\nAlso transcribed phonetically the Quechua and Aymara languages.'),(2,1,2,'Jakob','Runge','JR','runjak','gmail.com','https://github.com/runjak','Programmed this entire website (based on the structure of much simpler earlier versions by Paul Heggarty)..'),(3,1,3,'Hans-Jörg','Bibiko','HJB','bibiko','shh.mpg.de','http://www.eva.mpg.de/linguistics/staff/hans-joerg-bibiko/home.html','Website and server administrator and programmer.'),(111,11,11,'Warren','Maguire','WM','w.maguire','ed.ac.uk','http://www.lel.ed.ac.uk/~wmaguire/','Recorded and transcribed phonetically most of the accents of English.'),(121,1,12,'Giovanni','Abete','GA','giovanni.abete','gmail.com','https://unina.academia.edu/GiovanniAbete','Main phonetician for the Romance family. Transcribed most Romance varieties, and recorded most of those from southern Italy. Also main ‘narrow’ phonetic transcriber for the Malakula languages.'),(131,1,13,'Lechosław','Jocz','LJ','lechoslaw.jocz','gmail.com','https://pwsz-gorzow.academia.edu/Lechos%C5%82awJocz','Main phonetician for the Slavic family. Transcribed most Slavic varieties, and recorded many of these varieties, especially of Kashubian and Sorbian.'),(141,1,14,'Cormac','Anderson','CA','cormacanderson','gmail.com','https://amu.academia.edu/CormacAnderson','Main phonetician for the Celtic family. Transcribed most Celtic varieties, and recorded most of them, some with Paul Heggarty.'),

**Comment by PaulHeggarty** [comment]
I suspect tthat the error may be some problem with speech marks or characters somewhere in the csv, in one of the entries I've added or altered. I'll try to find which, but this shouldn't happen anyway.  It's a generalised problem with the upload system that I would love to be resolved.  It probably needs me to alter the system to create the csvs from Access.

**Comment by Bibiko** [comment]
I've tried to change the Import behaviour. If an error occurs while importing all changes will be ignored. @PaulHeggarty The problem with your `Contributors.txt` was that the `Contributor Ix` 401 occurred twice which isn't allowed (it's a primary key). I changed it (also mail address for Darja and my web address) and uploaded the file.
