### ISSUE TITLE
Uploading transcriptions via SQL not working properly

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#466]
I've just received the first batch of transcriptions (all number words, and a few other simple ones, like body parts) for all the new Saxon and Thuringian varieties for Sound Comparisons, produced the SQL file, and run it.  The results are weird, I can’t work out what's going on.
Where there are sound files already uploaded and working for a given language, the transcriptions fail to appear.  Otherwise, they do appear.

This is the latest file uploaded.  (There were some earlier attempts with lots of ".." entries for missing transcriptions -- I hope that was not the problem.)
[2017_11_21__Transcriptions_-_Germanic_-_Saxony_&_Thuringia.zip](https://github.com/lingdb/Sound-Comparisons/files/1490845/2017_11_21__Transcriptions_-_Germanic_-_Saxony_._Thuringia.zip)

**Comment by Bibiko** [comment]
The problem with the file `2017_11_21__Transcriptions_-Germanic-Saxony&_Thuringia.zip` is that there's a mismatch between language IDs and study name. E.g. the last statement: INSERT INTO Transcriptions_**Englishes** ...  for LanguageIx 11151256109 whereby 11151256109 is Erzgebirge W.: Stützengrün and belongs to study **Germanic**

**Comment by PaulHeggarty** [comment]
Great, thanks for the tip-off.  Must be a bug on my side, so I’ll try again!

**Comment by Bibiko** [comment]
... in addition, if one wants to know what's already in the database one can run the admin command `Diagnostics` > `General Study Check`

**Comment by PaulHeggarty** [comment]
Thanks.  Bug found and fixed in my sql creation code, and transcriptions now working fine on http://www.soundcomparisons.com/Germanic
